<?php
/**
 * Mail settings tab.
 *
 * @package Core_Blueprint
 * @since   1.0.0
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="wrap cb-core-wrap cb-core-mail-wrap">
	<h1 class="cb-core-title"><?php esc_html_e( 'Mail', 'core-blueprint' ); ?></h1>
	<p class="cb-core-intro"><?php esc_html_e( 'Configure reliable outbound email without a separate SMTP plugin. One transport can serve the default site sender and registered Core Blueprint sender identities such as Support, Billing or Coach.', 'core-blueprint' ); ?></p>

	<?php if ( is_array( $result ) && ! empty( $result['message'] ) ) : ?>
		<div class="notice <?php echo 'error' === ( $result['type'] ?? '' ) ? 'notice-error' : 'notice-success'; ?> inline"><p><?php echo esc_html( (string) $result['message'] ); ?></p></div>
	<?php endif; ?>

	<?php if ( '' !== $conflict_notice ) : ?>
		<?php echo $conflict_notice; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CB\Core\UI\Notice escapes all supplied content. ?>
	<?php endif; ?>

	<section class="cb-core-mail-section cb-core-mail-runtime">
		<h2><?php esc_html_e( 'Runtime status', 'core-blueprint' ); ?></h2>
		<div class="cb-core-mail-status-row">
			<?php echo $settings_runtime_status_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Status UI primitive. ?>
			<span><?php
			if ( $runtime_active ) {
				printf( esc_html__( 'Core Blueprint is delivering mail through %s.', 'core-blueprint' ), esc_html( $provider_label ) );
			} elseif ( '' !== $activation_error ) {
				echo esc_html( $activation_error );
			} elseif ( $enabled && ! empty( $conflicts ) ) {
				esc_html_e( 'Mail is enabled, but Core Blueprint intentionally registers no transport hooks while a conflict exists.', 'core-blueprint' );
			} else {
				esc_html_e( 'WordPress mail delivery is untouched by Core Blueprint.', 'core-blueprint' );
			}
			?></span>
		</div>
	</section>

	<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-form">
		<input type="hidden" name="action" value="cb_core_mail_save" />
		<?php wp_nonce_field( 'cb_core_mail_save' ); ?>

		<section class="cb-core-mail-section">
			<h2><?php esc_html_e( 'Delivery provider', 'core-blueprint' ); ?></h2>
			<div class="cb-core-field">
				<label class="cb-core-field__label" for="cb-mail-provider"><?php esc_html_e( 'Provider', 'core-blueprint' ); ?></label>
				<div class="cb-core-field__control">
					<select id="cb-mail-provider" name="provider">
						<option value="brevo" <?php selected( $settings['provider'], 'brevo' ); ?>><?php esc_html_e( 'Brevo API', 'core-blueprint' ); ?></option>
						<option value="smtp" <?php selected( $settings['provider'], 'smtp' ); ?>><?php esc_html_e( 'Generic SMTP', 'core-blueprint' ); ?></option>
					</select>
				</div>
				<p class="description"><?php esc_html_e( 'Brevo uses its HTTPS transactional email API. Generic SMTP is the provider-independent fallback for any standards-compliant mail server.', 'core-blueprint' ); ?></p>
			</div>
		</section>

		<section class="cb-core-mail-section">
			<h2><?php esc_html_e( 'Default sender', 'core-blueprint' ); ?></h2>
			<p class="description"><?php esc_html_e( 'The default sender is used for ordinary WordPress and system mail. Registered Core Blueprint extensions can use their own approved identity through the same delivery provider.', 'core-blueprint' ); ?></p>
			<div class="cb-core-mail-grid">
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-from-email"><?php esc_html_e( 'From Email', 'core-blueprint' ); ?></label>
					<input id="cb-mail-from-email" type="email" name="from_email" value="<?php echo esc_attr( (string) $settings['from_email'] ); ?>" autocomplete="email" />
					<p class="description"><?php esc_html_e( 'Use an address that is authorized by your mail provider.', 'core-blueprint' ); ?></p>
				</div>
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-from-name"><?php esc_html_e( 'From Name', 'core-blueprint' ); ?></label>
					<input id="cb-mail-from-name" type="text" name="from_name" value="<?php echo esc_attr( (string) $settings['from_name'] ); ?>" />
					<p class="description"><?php esc_html_e( 'The sender name recipients see for default site mail.', 'core-blueprint' ); ?></p>
				</div>
			</div>
			<label class="cb-core-check-row"><input type="checkbox" name="force_from_email" value="1" <?php checked( ! empty( $settings['force_from_email'] ) ); ?> /><span class="cb-core-check-row__body"><strong><?php esc_html_e( 'Force default From Email', 'core-blueprint' ); ?></strong><small><?php esc_html_e( 'Prevents ordinary themes and plugins from replacing the default sender. Registered Core Blueprint sender identities remain allowed.', 'core-blueprint' ); ?></small></span></label>
			<label class="cb-core-check-row"><input type="checkbox" name="force_from_name" value="1" <?php checked( ! empty( $settings['force_from_name'] ) ); ?> /><span class="cb-core-check-row__body"><strong><?php esc_html_e( 'Force default From Name', 'core-blueprint' ); ?></strong><small><?php esc_html_e( 'Prevents ordinary themes and plugins from replacing the default sender name. Registered Core Blueprint sender identities remain allowed.', 'core-blueprint' ); ?></small></span></label>
		</section>

		<?php if ( ! empty( $sender_identities ) ) : ?>
			<section class="cb-core-mail-section">
				<h2><?php esc_html_e( 'Registered sender identities', 'core-blueprint' ); ?></h2>
				<p class="description"><?php esc_html_e( 'Active Core Blueprint extensions register the sender roles they need. Configure a dedicated address here; leave a field blank to inherit the default sender above. Every address must be authorized by the selected delivery provider.', 'core-blueprint' ); ?></p>
				<?php foreach ( $sender_identities as $identity_id => $identity ) : ?>
					<?php
					$override = is_array( $sender_identity_overrides[ $identity_id ] ?? null ) ? $sender_identity_overrides[ $identity_id ] : [];
					$email_id = 'cb-mail-sender-email-' . $identity_id;
					$name_id  = 'cb-mail-sender-name-' . $identity_id;
					?>
					<div class="cb-core-field">
						<strong><?php echo esc_html( $identity['label'] ); ?></strong>
						<?php if ( '' !== $identity['description'] ) : ?>
							<p class="description"><?php echo esc_html( $identity['description'] ); ?></p>
						<?php endif; ?>
					</div>
					<div class="cb-core-mail-grid">
						<div class="cb-core-field">
							<label class="cb-core-field__label" for="<?php echo esc_attr( $email_id ); ?>"><?php esc_html_e( 'From Email', 'core-blueprint' ); ?></label>
							<input id="<?php echo esc_attr( $email_id ); ?>" type="email" name="sender_identity_email[<?php echo esc_attr( $identity_id ); ?>]" value="<?php echo esc_attr( (string) ( $override['email'] ?? '' ) ); ?>" placeholder="<?php echo esc_attr( $identity['email'] ); ?>" autocomplete="off" />
						</div>
						<div class="cb-core-field">
							<label class="cb-core-field__label" for="<?php echo esc_attr( $name_id ); ?>"><?php esc_html_e( 'From Name', 'core-blueprint' ); ?></label>
							<input id="<?php echo esc_attr( $name_id ); ?>" type="text" name="sender_identity_name[<?php echo esc_attr( $identity_id ); ?>]" value="<?php echo esc_attr( (string) ( $override['name'] ?? '' ) ); ?>" placeholder="<?php echo esc_attr( $identity['name'] ); ?>" />
						</div>
					</div>
				<?php endforeach; ?>
			</section>
		<?php endif; ?>

		<section class="cb-core-mail-section">
			<h2><?php esc_html_e( 'Brevo', 'core-blueprint' ); ?></h2>
			<div class="cb-core-field">
				<label class="cb-core-field__label" for="cb-mail-brevo-key"><?php esc_html_e( 'API key', 'core-blueprint' ); ?></label>
				<input id="cb-mail-brevo-key" type="password" name="brevo_api_key" value="" autocomplete="new-password" placeholder="<?php echo esc_attr( $has_brevo_secret ? __( 'Saved securely — leave blank to keep', 'core-blueprint' ) : __( 'Enter Brevo API key', 'core-blueprint' ) ); ?>" />
				<p class="description"><?php esc_html_e( 'Stored encrypted with libsodium and never written to Core Blueprint logs.', 'core-blueprint' ); ?></p>
			</div>
			<?php if ( $has_brevo_secret ) : ?>
				<label class="cb-core-check-row cb-core-check-row--compact"><input type="checkbox" name="clear_brevo_api_key" value="1" /><span class="cb-core-check-row__body"><?php esc_html_e( 'Remove saved Brevo API key', 'core-blueprint' ); ?></span></label>
			<?php endif; ?>
		</section>

		<section class="cb-core-mail-section">
			<h2><?php esc_html_e( 'Generic SMTP', 'core-blueprint' ); ?></h2>
			<div class="cb-core-mail-grid">
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-smtp-host"><?php esc_html_e( 'SMTP host', 'core-blueprint' ); ?></label>
					<input id="cb-mail-smtp-host" type="text" name="smtp_host" value="<?php echo esc_attr( (string) $settings['smtp_host'] ); ?>" autocomplete="off" />
				</div>
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-smtp-port"><?php esc_html_e( 'Port', 'core-blueprint' ); ?></label>
					<input id="cb-mail-smtp-port" type="number" min="1" max="65535" name="smtp_port" value="<?php echo esc_attr( (string) $settings['smtp_port'] ); ?>" />
				</div>
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-smtp-encryption"><?php esc_html_e( 'Encryption', 'core-blueprint' ); ?></label>
					<select id="cb-mail-smtp-encryption" name="smtp_encryption">
						<option value="tls" <?php selected( $settings['smtp_encryption'], 'tls' ); ?>>TLS</option>
						<option value="ssl" <?php selected( $settings['smtp_encryption'], 'ssl' ); ?>>SSL</option>
						<option value="none" <?php selected( $settings['smtp_encryption'], 'none' ); ?>><?php esc_html_e( 'None', 'core-blueprint' ); ?></option>
					</select>
				</div>
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-smtp-user"><?php esc_html_e( 'Username', 'core-blueprint' ); ?></label>
					<input id="cb-mail-smtp-user" type="text" name="smtp_username" value="<?php echo esc_attr( (string) $settings['smtp_username'] ); ?>" autocomplete="username" />
				</div>
				<div class="cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-smtp-pass"><?php esc_html_e( 'Password', 'core-blueprint' ); ?></label>
					<input id="cb-mail-smtp-pass" type="password" name="smtp_password" value="" autocomplete="new-password" placeholder="<?php echo esc_attr( $has_smtp_password ? __( 'Saved securely — leave blank to keep', 'core-blueprint' ) : __( 'Enter SMTP password', 'core-blueprint' ) ); ?>" />
				</div>
			</div>
			<label class="cb-core-check-row"><input type="checkbox" name="smtp_auth" value="1" <?php checked( ! empty( $settings['smtp_auth'] ) ); ?> /><span class="cb-core-check-row__body"><strong><?php esc_html_e( 'SMTP authentication', 'core-blueprint' ); ?></strong><small><?php esc_html_e( 'Authenticate with the configured username and encrypted password.', 'core-blueprint' ); ?></small></span></label>
			<label class="cb-core-check-row"><input type="checkbox" name="smtp_auto_tls" value="1" <?php checked( ! empty( $settings['smtp_auto_tls'] ) ); ?> /><span class="cb-core-check-row__body"><strong><?php esc_html_e( 'Automatic TLS', 'core-blueprint' ); ?></strong><small><?php esc_html_e( 'Allow PHPMailer to upgrade the connection to TLS when the server advertises support.', 'core-blueprint' ); ?></small></span></label>
			<?php if ( $has_smtp_password ) : ?>
				<label class="cb-core-check-row cb-core-check-row--compact"><input type="checkbox" name="clear_smtp_password" value="1" /><span class="cb-core-check-row__body"><?php esc_html_e( 'Remove saved SMTP password', 'core-blueprint' ); ?></span></label>
			<?php endif; ?>
		</section>

		<section class="cb-core-mail-section">
			<h2><?php esc_html_e( 'Mail log privacy', 'core-blueprint' ); ?></h2>
			<div class="cb-core-field">
				<label class="cb-core-field__label" for="cb-mail-retention"><?php esc_html_e( 'Retention', 'core-blueprint' ); ?></label>
				<select id="cb-mail-retention" name="retention_days">
					<?php foreach ( $retention_options as $days ) : ?>
						<option value="<?php echo esc_attr( (string) $days ); ?>" <?php selected( (int) $settings['retention_days'], $days ); ?>><?php printf( esc_html( _n( '%d day', '%d days', $days, 'core-blueprint' ) ), $days ); ?></option>
					<?php endforeach; ?>
				</select>
				<p class="description"><?php esc_html_e( 'The Mail Log stores delivery metadata only. Email bodies, attachment contents and credentials are never stored. Default retention is 14 days.', 'core-blueprint' ); ?></p>
			</div>
		</section>

		<div class="cb-core-actions">
			<button type="submit" class="button cb-core-button cb-core-button--primary"><?php esc_html_e( 'Save Mail settings', 'core-blueprint' ); ?></button>
		</div>
	</form>
</div>
