<?php
/** Mail Designer template surface. */
defined( 'ABSPATH' ) || exit;

$template_id = is_array( $current_template ) ? (string) ( $current_template['id'] ?? '' ) : '';
$project_json = is_array( $current_template )
	? wp_json_encode( $current_template['project'] ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE )
	: '{}';
$project_json = is_string( $project_json ) ? $project_json : '{}';
?>
<div class="wrap cb-core-wrap cb-core-mail-wrap cb-core-mail-designer-wrap">
	<h1 class="cb-core-title"><?php esc_html_e( 'Mail Templates', 'core-blueprint' ); ?></h1>
	<p class="cb-core-intro"><?php esc_html_e( 'Design system email presentation once in Core Blueprint. WordPress and installed extensions remain responsible for when mail is sent, to whom and with which domain data.', 'core-blueprint' ); ?></p>

	<?php if ( '' !== $result_notice_html ) : ?>
		<?php echo $result_notice_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Notice primitive. ?>
	<?php endif; ?>

	<?php if ( ! $designer_enabled ) : ?>
		<section class="cb-core-panel cb-core-mail-designer-disabled">
			<h2><?php esc_html_e( 'Mail Designer is disabled', 'core-blueprint' ); ?></h2>
			<p><?php esc_html_e( 'Enable the designer to customize WordPress system mail. This does not enable Core Blueprint SMTP or Brevo delivery.', 'core-blueprint' ); ?></p>
			<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
				<input type="hidden" name="action" value="cb_core_mail_features_save" />
				<input type="hidden" name="designer_enabled" value="1" />
				<?php if ( $delivery_enabled ) : ?><input type="hidden" name="delivery_enabled" value="1" /><?php endif; ?>
				<?php wp_nonce_field( 'cb_core_mail_features_save' ); ?>
				<button type="submit" class="button button-primary cb-core-button cb-core-button--primary"><?php esc_html_e( 'Enable Mail Designer', 'core-blueprint' ); ?></button>
			</form>
		</section>
	<?php elseif ( ! is_array( $current_template ) ) : ?>
		<section class="cb-core-panel"><h2><?php esc_html_e( 'No mail templates available', 'core-blueprint' ); ?></h2><p><?php esc_html_e( 'No active provider has registered a Mail Designer template.', 'core-blueprint' ); ?></p></section>
	<?php else : ?>
		<div
			class="cb-core-mail-designer"
			data-cb-mail-designer
			data-ajax-url="<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>"
			data-preview-nonce="<?php echo esc_attr( wp_create_nonce( 'cb_core_mail_designer_preview' ) ); ?>"
			data-template-id="<?php echo esc_attr( $template_id ); ?>"
		>
			<aside class="cb-core-mail-designer__templates" aria-label="<?php esc_attr_e( 'Mail templates', 'core-blueprint' ); ?>">
				<?php
				$current_group = '';
				foreach ( $templates as $definition ) :
					$group = (string) ( $definition['group'] ?? '' );
					if ( $group !== $current_group ) :
						if ( '' !== $current_group ) { echo '</div>'; }
						$current_group = $group;
						$group_label = 'wordpress' === $group ? __( 'WordPress', 'core-blueprint' ) : ucwords( str_replace( [ '-', '_' ], ' ', $group ) );
						?><h2 class="cb-core-mail-designer__group-title"><?php echo esc_html( $group_label ); ?></h2><div class="cb-core-mail-designer__template-list"><?php
					endif;
					$id = (string) ( $definition['id'] ?? '' );
					$url = add_query_arg( [ 'page' => \CB\Core\Mail\Admin\Page::SLUG, 'tab' => 'templates', 'template' => $id ], admin_url( 'admin.php' ) );
					?>
					<a class="cb-core-mail-designer__template-link <?php echo $id === $template_id ? 'is-active' : ''; ?>" href="<?php echo esc_url( $url ); ?>">
						<span><?php echo esc_html( (string) ( $definition['label'] ?? $id ) ); ?></span>
						<?php $resolved = \CB\Core\Mail\Designer\TemplateRepository::get( $id ); ?>
						<small><?php echo ! empty( $resolved['customized'] ) ? esc_html__( 'Customized', 'core-blueprint' ) : esc_html__( 'Default', 'core-blueprint' ); ?></small>
					</a>
				<?php endforeach; ?>
				<?php if ( '' !== $current_group ) { echo '</div>'; } ?>
			</aside>

			<main class="cb-core-mail-designer__workspace">
				<div class="cb-core-mail-designer__header">
					<div>
						<h2><?php echo esc_html( (string) $current_template['label'] ); ?></h2>
						<?php if ( '' !== (string) ( $current_template['description'] ?? '' ) ) : ?><p><?php echo esc_html( (string) $current_template['description'] ); ?></p><?php endif; ?>
					</div>
					<span class="cb-core-mail-template-state"><?php echo ! empty( $current_template['customized'] ) ? esc_html__( 'Customized', 'core-blueprint' ) : esc_html__( 'Provider default', 'core-blueprint' ); ?></span>
				</div>

				<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-designer__form" data-cb-mail-designer-form>
					<input type="hidden" name="action" value="cb_core_mail_template_save" />
					<input type="hidden" name="template_id" value="<?php echo esc_attr( $template_id ); ?>" />
					<?php wp_nonce_field( 'cb_core_mail_template_save' ); ?>
					<textarea name="project_json" data-cb-mail-project hidden><?php echo esc_textarea( $project_json ); ?></textarea>

					<div class="cb-core-mail-designer__subject cb-core-field">
						<label class="cb-core-field__label" for="cb-mail-designer-subject"><?php esc_html_e( 'Subject', 'core-blueprint' ); ?></label>
						<input id="cb-mail-designer-subject" type="text" name="subject" value="<?php echo esc_attr( (string) $current_template['subject'] ); ?>" required data-cb-mail-subject />
					</div>

					<div class="cb-core-mail-designer__toolbar" role="toolbar" aria-label="<?php esc_attr_e( 'Editor actions', 'core-blueprint' ); ?>">
						<div class="cb-core-mail-designer__toolbar-group">
							<button type="button" class="button cb-core-button" data-cb-mail-undo disabled><?php esc_html_e( 'Undo', 'core-blueprint' ); ?></button>
							<button type="button" class="button cb-core-button" data-cb-mail-redo disabled><?php esc_html_e( 'Redo', 'core-blueprint' ); ?></button>
						</div>
						<div class="cb-core-mail-designer__toolbar-group">
							<button type="button" class="button cb-core-button is-active" data-cb-mail-viewport="desktop"><?php esc_html_e( 'Desktop', 'core-blueprint' ); ?></button>
							<button type="button" class="button cb-core-button" data-cb-mail-viewport="mobile"><?php esc_html_e( 'Mobile', 'core-blueprint' ); ?></button>
						</div>
						<button type="submit" class="button button-primary cb-core-button cb-core-button--primary"><?php esc_html_e( 'Save template', 'core-blueprint' ); ?></button>
					</div>

					<div class="cb-core-mail-designer__editor-grid">
						<section class="cb-core-mail-designer__palette">
							<h3><?php esc_html_e( 'Elements', 'core-blueprint' ); ?></h3>
							<div class="cb-core-mail-designer__palette-list">
								<?php foreach ( [ 'heading' => __( 'Heading', 'core-blueprint' ), 'text' => __( 'Text', 'core-blueprint' ), 'button' => __( 'Button', 'core-blueprint' ), 'image' => __( 'Image', 'core-blueprint' ), 'divider' => __( 'Divider', 'core-blueprint' ), 'spacer' => __( 'Spacer', 'core-blueprint' ) ] as $type => $label ) : ?>
									<button type="button" class="button cb-core-mail-designer__element" data-cb-mail-add="<?php echo esc_attr( $type ); ?>"><?php echo esc_html( $label ); ?></button>
								<?php endforeach; ?>
							</div>

							<h3><?php esc_html_e( 'Dynamic data', 'core-blueprint' ); ?></h3>
							<p class="description"><?php esc_html_e( 'Click a token to copy it. Paste it into text, headings, buttons or URLs.', 'core-blueprint' ); ?></p>
							<div class="cb-core-mail-designer__bindings">
								<?php foreach ( $bindings as $binding ) : ?>
									<button type="button" class="cb-core-mail-binding" data-cb-mail-binding="<?php echo esc_attr( '{{' . (string) $binding['id'] . '}}' ); ?>" title="<?php echo esc_attr( (string) $binding['label'] ); ?>"><?php echo esc_html( '{{' . (string) $binding['id'] . '}}' ); ?></button>
								<?php endforeach; ?>
							</div>
						</section>

						<section class="cb-core-mail-designer__canvas-panel">
							<h3 class="screen-reader-text"><?php esc_html_e( 'Structure', 'core-blueprint' ); ?></h3>
							<div class="cb-core-mail-designer__canvas" data-cb-mail-canvas></div>
						</section>

						<aside class="cb-core-mail-designer__inspector" data-cb-mail-inspector>
							<h3><?php esc_html_e( 'Email style', 'core-blueprint' ); ?></h3>
							<p class="description"><?php esc_html_e( 'Select an element to edit it, or use these email-level controls.', 'core-blueprint' ); ?></p>
						</aside>
					</div>

					<section class="cb-core-mail-designer__preview-section">
						<div class="cb-core-mail-designer__preview-heading"><h3><?php esc_html_e( 'Live preview', 'core-blueprint' ); ?></h3><span data-cb-mail-preview-status aria-live="polite"></span></div>
						<div class="cb-core-mail-designer__preview-frame" data-cb-mail-preview-frame>
							<iframe title="<?php esc_attr_e( 'Mail preview', 'core-blueprint' ); ?>" sandbox="allow-popups allow-popups-to-escape-sandbox" data-cb-mail-preview srcdoc="<?php echo esc_attr( (string) ( $preview['html'] ?? '' ) ); ?>"></iframe>
						</div>
					</section>
				</form>

				<?php if ( ! empty( $current_template['customized'] ) ) : ?>
					<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-designer__reset-form">
						<input type="hidden" name="action" value="cb_core_mail_template_reset" />
						<input type="hidden" name="template_id" value="<?php echo esc_attr( $template_id ); ?>" />
						<?php wp_nonce_field( 'cb_core_mail_template_reset' ); ?>
						<button type="submit" class="button cb-core-button"><?php esc_html_e( 'Reset to provider default', 'core-blueprint' ); ?></button>
					</form>
				<?php endif; ?>
			</main>
		</div>
	<?php endif; ?>
</div>
