<?php
/** Mail test tab. */
defined( 'ABSPATH' ) || exit;
?>
<div class="wrap cb-core-wrap cb-core-mail-wrap">
	<h1 class="cb-core-title"><?php esc_html_e( 'Test Email', 'core-blueprint' ); ?></h1>
	<p class="cb-core-intro"><?php esc_html_e( 'Send a real message through the currently selected Core Blueprint Mail provider and record the result in the Mail Log.', 'core-blueprint' ); ?></p>

	<?php if ( '' !== $result_toast_message ) : ?>
		<div class="cb-core-mail-test-toast-payload" data-cb-core-mail-test-success="<?php echo esc_attr( $result_toast_message ); ?>" hidden></div>
	<?php endif; ?>

	<?php if ( '' !== $result_notice_html ) : ?>
		<div class="cb-core-mail-test-feedback">
			<?php echo $result_notice_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Notice UI primitive. ?>
		</div>
	<?php endif; ?>

	<section class="cb-core-mail-section cb-core-mail-test-section">
		<h2><?php esc_html_e( 'Delivery status', 'core-blueprint' ); ?></h2>
		<dl class="cb-core-mail-status-list">
			<div class="cb-core-mail-status-list__row">
				<dt><?php esc_html_e( 'Module', 'core-blueprint' ); ?></dt>
				<dd><?php echo $module_status_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Status UI primitive. ?></dd>
			</div>
			<div class="cb-core-mail-status-list__row">
				<dt><?php esc_html_e( 'Provider', 'core-blueprint' ); ?></dt>
				<dd><?php echo esc_html( $provider_label ); ?></dd>
			</div>
			<div class="cb-core-mail-status-list__row">
				<dt><?php esc_html_e( 'Runtime', 'core-blueprint' ); ?></dt>
				<dd><?php echo $runtime_status_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Status UI primitive. ?></dd>
			</div>
			<?php if ( '' !== $conflict_status_html ) : ?>
				<div class="cb-core-mail-status-list__row">
					<dt><?php esc_html_e( 'Conflict', 'core-blueprint' ); ?></dt>
					<dd><?php echo $conflict_status_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Status UI primitive. ?></dd>
				</div>
			<?php endif; ?>
		</dl>
	</section>

	<section class="cb-core-mail-section cb-core-mail-test-section">
		<h2><?php esc_html_e( 'Send test', 'core-blueprint' ); ?></h2>
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-test-form">
			<input type="hidden" name="action" value="cb_core_mail_test" />
			<?php wp_nonce_field( 'cb_core_mail_test' ); ?>
			<div class="cb-core-field cb-core-mail-test-recipient">
				<label class="cb-core-field__label" for="cb-mail-test-email"><?php esc_html_e( 'Recipient', 'core-blueprint' ); ?></label>
				<div class="cb-core-field__control cb-core-mail-test-action-row">
					<input id="cb-mail-test-email" type="email" name="test_email" value="<?php echo esc_attr( (string) wp_get_current_user()->user_email ); ?>" required />
					<button type="submit" class="button cb-core-button cb-core-button--primary" <?php disabled( ! $runtime_active ); ?>><?php esc_html_e( 'Send test email', 'core-blueprint' ); ?></button>
				</div>
				<p class="description"><?php esc_html_e( 'The message contains no site secrets or diagnostic dump; it only confirms delivery.', 'core-blueprint' ); ?></p>
			</div>
		</form>
	</section>
</div>
