<?php
/** Mail capability overview. */
defined( 'ABSPATH' ) || exit;
?>
<div class="wrap cb-core-wrap cb-core-mail-wrap">
	<h1 class="cb-core-title"><?php esc_html_e( 'Mail', 'core-blueprint' ); ?></h1>
	<p class="cb-core-intro"><?php esc_html_e( 'Choose which Core Blueprint mail capabilities this site owns. Mail Designer changes presentation; Mail Delivery changes transport. They can be used independently.', 'core-blueprint' ); ?></p>

	<?php if ( '' !== $result_notice_html ) : ?>
		<?php echo $result_notice_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Notice primitive. ?>
	<?php endif; ?>

	<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-feature-form">
		<input type="hidden" name="action" value="cb_core_mail_features_save" />
		<?php wp_nonce_field( 'cb_core_mail_features_save' ); ?>

		<div class="cb-core-mail-feature-grid">
			<section class="cb-core-panel cb-core-mail-feature-card">
				<div class="cb-core-mail-feature-card__heading">
					<div>
						<h2><?php esc_html_e( 'Mail Designer', 'core-blueprint' ); ?></h2>
						<p><?php esc_html_e( 'Design WordPress system emails with the Core Blueprint Design Foundation. Extensions can add templates, bindings and domain-specific blocks to the same designer.', 'core-blueprint' ); ?></p>
					</div>
					<?php echo $designer_status_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Status primitive. ?>
				</div>
				<label class="cb-core-check-row">
					<input type="checkbox" name="designer_enabled" value="1" <?php checked( $designer_enabled ); ?> />
					<span class="cb-core-check-row__body"><strong><?php esc_html_e( 'Enable Mail Designer', 'core-blueprint' ); ?></strong><small><?php esc_html_e( 'When disabled, WordPress and extension email presentation remains untouched.', 'core-blueprint' ); ?></small></span>
				</label>
			</section>

			<section class="cb-core-panel cb-core-mail-feature-card">
				<div class="cb-core-mail-feature-card__heading">
					<div>
						<h2><?php esc_html_e( 'Mail Delivery', 'core-blueprint' ); ?></h2>
						<p><?php esc_html_e( 'Route WordPress mail through the configured Core Blueprint SMTP or Brevo transport, with sender identities and privacy-first delivery logging.', 'core-blueprint' ); ?></p>
					</div>
					<?php echo $delivery_status_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Status primitive. ?>
				</div>
				<label class="cb-core-check-row">
					<input type="checkbox" name="delivery_enabled" value="1" <?php checked( $delivery_enabled ); ?> />
					<span class="cb-core-check-row__body"><strong><?php esc_html_e( 'Enable Mail Delivery', 'core-blueprint' ); ?></strong><small><?php esc_html_e( 'When disabled, Core Blueprint registers no SMTP or Brevo transport hooks.', 'core-blueprint' ); ?></small></span>
				</label>
			</section>
		</div>

		<p class="submit"><button type="submit" class="button button-primary cb-core-button cb-core-button--primary"><?php esc_html_e( 'Save mail capabilities', 'core-blueprint' ); ?></button></p>
	</form>
</div>
