<?php
/** Mail Designer template surface. */
defined( 'ABSPATH' ) || exit;

$template_id = is_array( $current_template ) ? (string) ( $current_template['id'] ?? '' ) : '';
$project_json = is_array( $current_template )
	? wp_json_encode( $current_template['project'] ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE )
	: '{}';
$project_json = is_string( $project_json ) ? $project_json : '{}';
$components_json = wp_json_encode( $components ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
$components_json = is_string( $components_json ) ? $components_json : '{}';
/* translators: WordPress core owns these generic editor UI labels in the default text domain. */
$fullscreen_label = __( 'Fullscreen mode', 'default' ); // phpcs:ignore WordPress.WP.I18n.TextDomainMismatch -- intentional WordPress platform vocabulary.
$tablet_label = __( 'Tablet', 'default' ); // phpcs:ignore WordPress.WP.I18n.TextDomainMismatch -- intentional WordPress platform vocabulary.
$template_groups = [];
foreach ( (array) $templates as $definition ) {
	if ( ! is_array( $definition ) ) {
		continue;
	}
	$group = (string) ( $definition['group'] ?? '' );
	$group = '' !== $group ? $group : 'other';
	$template_groups[ $group ][] = $definition;
}
?>
<div class="wrap cb-core-wrap cb-core-mail-wrap cb-core-mail-designer-wrap">
	<h1 class="cb-core-title"><?php esc_html_e( 'Mail Templates', 'core-blueprint' ); ?></h1>
	<p class="cb-core-intro"><?php esc_html_e( 'Design system email presentation once in Core Blueprint. WordPress and installed extensions remain responsible for when mail is sent, to whom and with which domain data.', 'core-blueprint' ); ?></p>

	<?php if ( '' !== $result_notice_html ) : ?>
		<?php echo $result_notice_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by shared Notice primitive. ?>
	<?php endif; ?>

	<?php if ( ! $designer_enabled ) : ?>
		<section class="cb-core-panel cb-core-mail-designer-disabled">
			<h2><?php esc_html_e( 'Mail Designer is disabled', 'core-blueprint' ); ?></h2>
			<p><?php esc_html_e( 'Enable the designer to customize WordPress system mail. This does not enable Core Blueprint SMTP or Brevo delivery.', 'core-blueprint' ); ?></p>
			<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
				<input type="hidden" name="action" value="cb_core_mail_features_save" />
				<input type="hidden" name="designer_enabled" value="1" />
				<?php if ( $delivery_enabled ) : ?><input type="hidden" name="delivery_enabled" value="1" /><?php endif; ?>
				<?php wp_nonce_field( 'cb_core_mail_features_save' ); ?>
				<button type="submit" class="button button-primary cb-core-button cb-core-button--primary"><?php esc_html_e( 'Enable Mail Designer', 'core-blueprint' ); ?></button>
			</form>
		</section>
	<?php elseif ( ! is_array( $current_template ) ) : ?>
		<section class="cb-core-panel"><h2><?php esc_html_e( 'No mail templates available', 'core-blueprint' ); ?></h2><p><?php esc_html_e( 'No active provider has registered a Mail Designer template.', 'core-blueprint' ); ?></p></section>
	<?php else : ?>
		<div
			class="cb-core-mail-designer"
			data-cb-mail-designer
			data-cb-design-launch-root
			data-ajax-url="<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>"
			data-preview-nonce="<?php echo esc_attr( wp_create_nonce( 'cb_core_mail_designer_preview' ) ); ?>"
			data-template-id="<?php echo esc_attr( $template_id ); ?>"
		>
			<section class="cb-core-panel cb-core-mail-designer__context" data-cb-design-launch-context aria-label="<?php esc_attr_e( 'Mail template context', 'core-blueprint' ); ?>">
				<div class="cb-core-mail-designer__template-control cb-core-field">
					<label class="cb-core-field__label" for="cb-mail-designer-template"><?php esc_html_e( 'Template', 'core-blueprint' ); ?></label>
					<select id="cb-mail-designer-template" data-cb-mail-template-select>
						<?php foreach ( $template_groups as $group => $definitions ) : ?>
							<?php $group_label = 'wordpress' === $group ? __( 'WordPress', 'core-blueprint' ) : ucwords( str_replace( [ '-', '_' ], ' ', $group ) ); ?>
							<optgroup label="<?php echo esc_attr( $group_label ); ?>">
								<?php foreach ( $definitions as $definition ) : ?>
									<?php
									$id = (string) ( $definition['id'] ?? '' );
									$url = add_query_arg( [ 'page' => \CB\Core\Mail\Admin\Page::SLUG, 'tab' => 'templates', 'template' => $id ], admin_url( 'admin.php' ) );
									$resolved = \CB\Core\Mail\Designer\TemplateRepository::get( $id );
									$state_label = ! empty( $resolved['customized'] ) ? __( 'Customized', 'core-blueprint' ) : __( 'Default', 'core-blueprint' );
									?>
									<option value="<?php echo esc_url( $url ); ?>" <?php selected( $id, $template_id ); ?>><?php echo esc_html( (string) ( $definition['label'] ?? $id ) . ' — ' . $state_label ); ?></option>
								<?php endforeach; ?>
							</optgroup>
						<?php endforeach; ?>
					</select>
					<?php if ( '' !== (string) ( $current_template['description'] ?? '' ) ) : ?><p class="description"><?php echo esc_html( (string) $current_template['description'] ); ?></p><?php endif; ?>
				</div>
				<div class="cb-core-mail-designer__context-state">
					<strong><?php echo esc_html( (string) $current_template['label'] ); ?></strong>
					<span class="cb-core-mail-template-state"><?php echo ! empty( $current_template['customized'] ) ? esc_html__( 'Customized', 'core-blueprint' ) : esc_html__( 'Using default template', 'core-blueprint' ); ?></span>
				</div>
			</section>

			<main class="cb-core-mail-designer__workspace">
				<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-designer__form" data-cb-mail-designer-form>
					<input type="hidden" name="action" value="cb_core_mail_template_save" />
					<input type="hidden" name="template_id" value="<?php echo esc_attr( $template_id ); ?>" />
					<?php wp_nonce_field( 'cb_core_mail_template_save' ); ?>
					<textarea name="project_json" data-cb-mail-project hidden><?php echo esc_textarea( $project_json ); ?></textarea>
					<textarea data-cb-mail-components hidden><?php echo esc_textarea( $components_json ); ?></textarea>

					<div class="cb-core-mail-designer__subject cb-core-field">
						<label class="cb-core-field__label" for="cb-mail-designer-subject"><?php esc_html_e( 'Subject', 'core-blueprint' ); ?></label>
						<input id="cb-mail-designer-subject" type="text" name="subject" value="<?php echo esc_attr( (string) $current_template['subject'] ); ?>" required data-cb-mail-subject />
					</div>

					<div class="cb-core-design-shell" data-cb-design-shell>
						<div class="cb-core-design-shell__toolbar cb-core-mail-designer__toolbar" role="toolbar" aria-label="<?php esc_attr_e( 'Editor actions', 'core-blueprint' ); ?>">
							<div class="cb-core-design-shell__toolbar-group">
								<span class="cb-core-mail-designer__toolbar-label" data-cb-design-shell-group-label><?php esc_html_e( 'History', 'core-blueprint' ); ?></span>
								<button type="button" class="button cb-core-button" data-cb-design-shell-undo disabled><?php esc_html_e( 'Undo', 'core-blueprint' ); ?></button>
								<button type="button" class="button cb-core-button" data-cb-design-shell-redo disabled><?php esc_html_e( 'Redo', 'core-blueprint' ); ?></button>
							</div>
							<div class="cb-core-design-shell__toolbar-group" data-cb-design-shell-viewport-group>
								<span class="cb-core-mail-designer__toolbar-label" data-cb-design-shell-group-label><?php esc_html_e( 'Canvas', 'core-blueprint' ); ?></span>
								<button type="button" class="button cb-core-button is-active" data-cb-design-shell-viewport="desktop" data-cb-mail-viewport="desktop" aria-pressed="true"><?php esc_html_e( 'Desktop', 'core-blueprint' ); ?></button>
								<button type="button" class="button cb-core-button" data-cb-design-shell-viewport="tablet" data-cb-mail-viewport="tablet" aria-pressed="false"><?php echo esc_html( $tablet_label ); ?></button>
								<button type="button" class="button cb-core-button" data-cb-design-shell-viewport="mobile" data-cb-mail-viewport="mobile" aria-pressed="false"><?php esc_html_e( 'Mobile', 'core-blueprint' ); ?></button>
							</div>
							<div class="cb-core-design-shell__toolbar-group">
								<button type="button" class="button cb-core-button" data-cb-design-shell-fullscreen aria-pressed="false" aria-label="<?php echo esc_attr( $fullscreen_label ); ?>"><?php echo esc_html( $fullscreen_label ); ?></button>
							</div>
							<div class="cb-core-mail-designer__toolbar-status" data-cb-design-shell-status data-cb-mail-preview-status aria-live="polite"></div>
							<button type="submit" class="button button-primary cb-core-button cb-core-button--primary" data-cb-design-shell-primary-action><?php esc_html_e( 'Save template', 'core-blueprint' ); ?></button>
						</div>

						<div class="cb-core-design-shell__workspace">
							<section class="cb-core-design-shell__palette cb-core-design-shell__palette--tabbed cb-core-mail-designer__palette" aria-label="<?php esc_attr_e( 'Mail content', 'core-blueprint' ); ?>">
								<div class="cb-core-design-shell__tabs" role="tablist" aria-label="<?php esc_attr_e( 'Mail content panels', 'core-blueprint' ); ?>">
									<button type="button" class="cb-core-design-shell__tab is-active" role="tab" aria-selected="true" data-cb-design-shell-group="palette" data-cb-design-shell-tab="elements"><?php esc_html_e( 'Elements', 'core-blueprint' ); ?></button>
									<button type="button" class="cb-core-design-shell__tab" role="tab" aria-selected="false" data-cb-design-shell-group="palette" data-cb-design-shell-tab="dynamic-data"><?php esc_html_e( 'Dynamic data', 'core-blueprint' ); ?></button>
								</div>
								<div class="cb-core-design-shell__panel" data-cb-design-shell-group="palette" data-cb-design-shell-panel="elements">
									<div class="cb-core-mail-designer__palette-list">
										<?php foreach ( $components as $component_id => $component ) : ?>
											<button type="button" class="button cb-core-mail-designer__element" data-cb-mail-add="<?php echo esc_attr( (string) $component_id ); ?>">
												<?php echo esc_html( (string) ( $component['label'] ?? $component_id ) ); ?>
												<?php if ( 'core' !== (string) ( $component['provider'] ?? 'core' ) ) : ?><small><?php echo esc_html( (string) $component['provider'] ); ?></small><?php endif; ?>
											</button>
										<?php endforeach; ?>
									</div>
								</div>
								<div class="cb-core-design-shell__panel" data-cb-design-shell-group="palette" data-cb-design-shell-panel="dynamic-data" hidden>
									<p class="description"><?php esc_html_e( 'Click a token to copy it. Paste it into text, headings, buttons or URLs.', 'core-blueprint' ); ?></p>
									<div class="cb-core-mail-designer__bindings">
										<?php foreach ( $bindings as $binding ) : ?>
											<button type="button" class="cb-core-mail-binding" data-cb-mail-binding="<?php echo esc_attr( '{{' . (string) $binding['id'] . '}}' ); ?>" title="<?php echo esc_attr( (string) $binding['label'] ); ?>"><?php echo esc_html( '{{' . (string) $binding['id'] . '}}' ); ?></button>
										<?php endforeach; ?>
									</div>
								</div>
							</section>

							<section class="cb-core-design-shell__canvas cb-core-mail-designer__canvas-panel" aria-label="<?php esc_attr_e( 'Visual mail canvas', 'core-blueprint' ); ?>">
								<div class="cb-core-mail-designer__canvas-heading">
									<div>
										<strong><?php esc_html_e( 'Visual canvas', 'core-blueprint' ); ?></strong>
										<span><?php esc_html_e( 'Click an email element to inspect and edit it.', 'core-blueprint' ); ?></span>
									</div>
								</div>
								<div class="cb-core-mail-designer__preview-frame" data-cb-mail-preview-frame>
									<iframe title="<?php esc_attr_e( 'Editable mail preview', 'core-blueprint' ); ?>" sandbox="allow-same-origin allow-popups allow-popups-to-escape-sandbox" data-cb-mail-preview srcdoc="<?php echo esc_attr( (string) ( $preview['html'] ?? '' ) ); ?>"></iframe>
								</div>
							</section>

							<aside class="cb-core-design-shell__sidebar cb-core-mail-designer__sidebar" aria-label="<?php esc_attr_e( 'Designer controls', 'core-blueprint' ); ?>">
								<div class="cb-core-design-shell__tabs" role="tablist" aria-label="<?php esc_attr_e( 'Designer panels', 'core-blueprint' ); ?>">
									<button type="button" class="cb-core-design-shell__tab is-active" role="tab" aria-selected="true" data-cb-design-shell-tab="email" data-cb-design-shell-sidebar-role="settings"><?php esc_html_e( 'Email', 'core-blueprint' ); ?></button>
									<button type="button" class="cb-core-design-shell__tab" role="tab" aria-selected="false" data-cb-design-shell-tab="structure" data-cb-design-shell-sidebar-role="layers"><?php esc_html_e( 'Structure', 'core-blueprint' ); ?></button>
									<button type="button" class="cb-core-design-shell__tab" role="tab" aria-selected="false" data-cb-design-shell-tab="inspector" data-cb-design-shell-sidebar-role="inspector"><?php esc_html_e( 'Inspector', 'core-blueprint' ); ?></button>
								</div>
								<div class="cb-core-design-shell__panel" data-cb-design-shell-panel="email" data-cb-design-shell-sidebar-role="settings">
									<div data-cb-mail-email-inspector></div>
								</div>
								<div class="cb-core-design-shell__panel" data-cb-design-shell-panel="structure" data-cb-design-shell-sidebar-role="layers" hidden>
									<div data-cb-mail-structure></div>
								</div>
								<div class="cb-core-design-shell__panel" data-cb-design-shell-panel="inspector" data-cb-design-shell-sidebar-role="inspector" hidden>
									<div data-cb-mail-inspector>
										<p class="description"><?php esc_html_e( 'Select an element on the canvas or in Structure to edit it.', 'core-blueprint' ); ?></p>
									</div>
								</div>
							</aside>
						</div>
					</div>
				</form>

				<?php if ( ! empty( $current_template['customized'] ) ) : ?>
					<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cb-core-mail-designer__reset-form">
						<input type="hidden" name="action" value="cb_core_mail_template_reset" />
						<input type="hidden" name="template_id" value="<?php echo esc_attr( $template_id ); ?>" />
						<?php wp_nonce_field( 'cb_core_mail_template_reset' ); ?>
						<button type="submit" class="button cb-core-button"><?php esc_html_e( 'Reset to provider default', 'core-blueprint' ); ?></button>
					</form>
				<?php endif; ?>
			</main>
		</div>
	<?php endif; ?>
</div>