<?php
declare(strict_types=1);
/**
 * Admin
 *
 * Owns Core Blueprint's admin infrastructure:
 *   - the Core Blueprint parent menu (registered if no sibling plugin has)
 *   - asset enqueue for all Core Blueprint admin screens
 *
 * Page rendering is NOT this class's job - each page is its own class
 * implementing Page, registered with PageRegistry.
 *
 * @package Core_Blueprint
 * @since   1.0.0
 */

namespace CB\Core\Admin;

use CB\Core\Admin\Pages\Dashboard;
use CB\Core\Admin\Pages\Logs;
use CB\Core\Admin\Pages\Preferences;
use CB\Core\Admin\Pages\Safeguards;
use CB\Core\UI;

defined( 'ABSPATH' ) || exit;

final class Admin {

	// ─── Slug constants ──────────────────────────────────────────────────
	// Kept public so templates and sibling CB plugins can reference them.
	// Actual registration is in the per-page classes.

	const MENU_SLUG        = 'core-blueprint';
	const LOGS_SLUG        = 'core-blueprint-logs';
	const SAFEGUARDS_SLUG  = 'core-blueprint-safeguards';
	const PREFERENCES_SLUG = 'core-blueprint-preferences';
	const CONSOLE_SLUG     = 'core-blueprint-console';

	public static function init(): void {
		add_action( 'admin_menu',            [ __CLASS__, 'register_parent_menu' ], 5 );
		add_action( 'admin_menu',            [ __CLASS__, 'remove_duplicate_submenu' ], 999 );
		add_action( 'admin_enqueue_scripts', [ __CLASS__, 'enqueue_assets' ] );

		// Register Core Blueprint's own pages at the right moment. Sibling
		// CB plugins do the same via this hook.
		add_action( 'cb_core_register_pages', [ __CLASS__, 'register_foundation_pages' ] );
	}

	// ─── Parent menu ──────────────────────────────────────────────────────

	/**
	 * Register the Core Blueprint top-level menu if no sibling CB plugin has
	 * already done so. Defensive - multiple CB plugins might race, and the
	 * first one wins.
	 */
	public static function register_parent_menu(): void {
		global $menu;

		$parent_exists = false;
		if ( is_array( $menu ) ) {
			foreach ( $menu as $item ) {
				if ( isset( $item[2] ) && CB_CORE_PARENT_MENU === $item[2] ) {
					$parent_exists = true;
					break;
				}
			}
		}

		if ( ! $parent_exists ) {
			add_menu_page(
				'Core Blueprint',
				'Core Blueprint',
				/**
				 * Filter: cb_core_menu_capability
				 *
				 * The capability required to see Core Blueprint admin pages.
				 * Defaults to 'manage_options'.
				 */
				(string) apply_filters( 'cb_core_menu_capability', 'manage_options' ),
				CB_CORE_PARENT_MENU,
				[ __CLASS__, 'render_parent_landing' ],
				self::get_menu_icon(),
				3
			);
		}
	}

	/**
	 * Called when a user clicks the Core Blueprint parent menu item itself.
	 * Delegates to the registered Dashboard page, falling back to a simple
	 * notice when no dashboard is available.
	 */
	public static function render_parent_landing(): void {
		if ( class_exists( Dashboard::class ) ) {
			$dashboard = new Dashboard();
			$dashboard->render();
			return;
		}
		echo '<div class="wrap"><h1>Core Blueprint</h1><p>';
		esc_html_e( 'Dashboard not available.', 'core-blueprint' );
		echo '</p></div>';
	}

	/**
	 * Register Core Blueprint's own pages with the registry. Called from the
	 * cb_core_register_pages action so the timing aligns with admin_menu.
	 *
	 * Submenu order is controlled by each page's position(). Resulting
	 * sidebar order:
	 *   Dashboard (auto-gen, slug = parent)
	 *   Logs         - position 20
	 *   Safeguards   - position 30
	 *   Preferences  - position 90
	 *   Beacon      - optional extension page, position 100
	 */
	public static function register_foundation_pages(): void {
		// Dashboard is NOT registered here. It lives as the auto-generated
		// first submenu that add_menu_page() creates in register_parent_menu().
		// That auto-gen entry has slug == parent slug, so WordPress uses it
		// as the parent-click landing page. Its callback is render_parent_landing,
		// which instantiates Dashboard and renders it. remove_duplicate_submenu()
		// below relabels the auto-gen to "Dashboard" (instead of the parent's
		// "Core Blueprint" label) for cleaner sidebar presentation.

		PageRegistry::register_base( new Logs() );
		PageRegistry::register_base( new Safeguards() );
		PageRegistry::register_base( new Preferences() );
	}

	public static function remove_duplicate_submenu(): void {
		global $submenu;

		// The first submenu under the parent is auto-generated by add_menu_page()
		// and inherits the parent's "Core Blueprint" label, which is ugly in the
		// sidebar. Rewrite its label + title to "Dashboard" in place - keeping
		// the entry (and its callback = render_parent_landing, which renders
		// Dashboard) so clicking the parent menu still lands on the Dashboard.
		if ( isset( $submenu[ CB_CORE_PARENT_MENU ] ) ) {
			foreach ( $submenu[ CB_CORE_PARENT_MENU ] as $i => $item ) {
				if ( isset( $item[2] ) && CB_CORE_PARENT_MENU === $item[2] ) {
					$submenu[ CB_CORE_PARENT_MENU ][ $i ][0] = __( 'Dashboard', 'core-blueprint' );
					if ( isset( $submenu[ CB_CORE_PARENT_MENU ][ $i ][3] ) ) {
						$submenu[ CB_CORE_PARENT_MENU ][ $i ][3] = __( 'Dashboard', 'core-blueprint' );
					}
					break;
				}
			}
		}

		// Suppress the Core Blueprint Theme's Site Mode submenu - this plugin
		// owns access mode now. Safe no-op if the theme is not active or has
		// already been updated to drop its own submenu.
		remove_submenu_page( CB_CORE_PARENT_MENU, 'core-blueprint-site-mode' );
	}

	// ─── Asset enqueuing ─────────────────────────────────────────────────

	public static function enqueue_assets( string $hook ): void {
		// Detect Core Blueprint screens via three mechanisms (any match wins):
		//   1. Registry-tracked hook_suffixes - pages that registered
		//      themselves via PageRegistry
		//   2. The parent toplevel hook
		//   3. Pattern match - any 'core-blueprint_page_cb-*' or
		//      'core-blueprint_page_core-blueprint-*' hook, catches pages
		//      registered by sibling CB plugins (Invoice, Access Control,
		//      Protected Content) even when they don't go through the registry.
		$registry_hooks = PageRegistry::all_hook_suffixes();
		$is_cb_screen = in_array( $hook, $registry_hooks, true )
			|| $hook === 'toplevel_page_' . CB_CORE_PARENT_MENU
			|| ( 0 === strpos( $hook, CB_CORE_PARENT_MENU . '_page_cb-' ) )
			|| ( 0 === strpos( $hook, CB_CORE_PARENT_MENU . '_page_core-blueprint-' ) );

		if ( ! $is_cb_screen ) {
			return;
		}

		// ─── Tokens (1.1.0) ──────────────────────────────────────────────
		//
		// Design tokens (--cb-*) live in their own stylesheet so they
		// can be enqueued ahead of everything else, and so portal
		// elements (dialogs, toasts) appended outside .cb-core-wrap
		// can resolve them via html[data-cb-theme="..."] scope. See
		// the comment block at the top of tokens.css for the scope
		// rationale.
		wp_enqueue_style(
			'cb-core-css-tokens',
			CB_CORE_URL . 'assets/css/tokens.css',
			[],
			CB_CORE_VERSION
		);

		// Shared Lucide primitive. Kept behind UI\Assets so standalone
		// WordPress admin pages can opt into icons without the Core Admin Theme.
		\CB\Core\UI\Assets::enqueue_icons();

		// Registered Core Admin pages may declare semantic shared-UI requirements.
		// PageRegistry resolves those identifiers to private assets; extensions never
		// depend on handles or filenames. The legacy sibling-pattern detection above
		// remains transitional until BASE-10E and is not a public screen contract.
		PageRegistry::enqueue_requirements_for_hook( $hook );

		// Preferences → CLI consumes the shared Clipboard Foundation. Keep the
		// clipboard runtime scoped to this tab rather than loading it across all
		// Core Admin screens.
		$screen_context     = ScreenContext::from_request( $hook );
		$current_page       = $screen_context->page();
		$current_tab        = $screen_context->tab();
		$is_cli_preferences      = 'core-blueprint-preferences' === $current_page && 'cli' === $current_tab;
		$is_hud_menu_preferences = 'core-blueprint-preferences' === $current_page && 'floating-menu' === $current_tab;
		$is_mail_settings        = 'core-blueprint-mail' === $current_page && ( '' === $current_tab || 'settings' === $current_tab );
		$is_mail_test       = 'core-blueprint-mail' === $current_page && 'test' === $current_tab;
		$is_mail_log        = ( 'core-blueprint-mail' === $current_page && 'logs' === $current_tab )
			|| ( self::LOGS_SLUG === $current_page && 'mail' === $current_tab );
		$current_view       = $screen_context->view();
		$is_content_models_page = 'core-blueprint-content-models' === $current_page;
		$is_media_formats_page = 'core-blueprint-media-formats' === $current_page;
		$is_content_models_field_groups = $is_content_models_page && 'field-groups' === $current_tab && in_array( $current_view, [ 'edit', 'field' ], true );
		$is_access_mode_page = 'core-blueprint-safeguards' === $current_page && 'access-mode' === $current_tab;

		if ( $is_access_mode_page ) {
			\CB\Core\UI\Assets::enqueue_object_picker( \CB\Core\UI\Assets::OBJECT_PICKER_PRESENTATION_CORE );
			\CB\Core\UI\Assets::enqueue_time_picker( \CB\Core\UI\Assets::TIME_PICKER_PRESENTATION_CORE );
		}

		if ( $is_cli_preferences ) {
			\CB\Core\UI\Assets::enqueue_clipboard( \CB\Core\UI\Assets::CLIPBOARD_PRESENTATION_CORE );

			wp_enqueue_script_module(
				'@cb-core/preferences-cli',
				CB_CORE_URL . 'assets/js/features/preferences-cli.js',
				[ '@cb-core/clipboard' ],
				CB_CORE_VERSION
			);
			add_filter(
				'script_module_data_@cb-core/preferences-cli',
				static function ( array $existing ): array {
					return array_merge( $existing, [
						'ajaxUrl' => admin_url( 'admin-ajax.php' ),
						'i18n' => [
							'copyCommand' => __( 'Copy command', 'core-blueprint' ),
						],
					] );
				}
			);
		}

		if ( $is_hud_menu_preferences ) {
			wp_enqueue_script_module(
				'@cb-core/preferences-floating-menu',
				CB_CORE_URL . 'assets/js/features/preferences-floating-menu.js',
				[],
				CB_CORE_VERSION
			);
			add_filter(
				'script_module_data_@cb-core/preferences-floating-menu',
				static function ( array $existing ): array {
					return array_merge( $existing, [
						'i18n' => [
							'labelRequired' => __( 'Enter a label for the custom link.', 'core-blueprint' ),
							'urlInvalid'    => __( 'Enter a valid http or https URL.', 'core-blueprint' ),
							'sectionInvalid'=> __( 'Choose an available menu section.', 'core-blueprint' ),
						],
					] );
				}
			);
		}

		if ( $is_mail_settings ) {
			wp_enqueue_script_module(
				'@cb-core/mail-settings',
				CB_CORE_URL . 'assets/js/features/mail-settings.js',
				[],
				CB_CORE_VERSION
			);
		}

		if ( $is_mail_test ) {
			\CB\Core\UI\Assets::enqueue_toasts( \CB\Core\UI\Assets::TOAST_PRESENTATION_CORE );

			wp_enqueue_script_module(
				'@cb-core/mail-test',
				CB_CORE_URL . 'assets/js/features/mail-test.js',
				[ '@cb-core/toast' ],
				CB_CORE_VERSION
			);
		}

		if ( $is_mail_log ) {
			\CB\Core\UI\Assets::enqueue_modals( \CB\Core\UI\Assets::MODAL_PRESENTATION_CORE );

			wp_enqueue_script_module(
				'@cb-core/mail-log',
				CB_CORE_URL . 'assets/js/features/mail-log.js',
				[ '@cb-core/modal' ],
				CB_CORE_VERSION
			);
		}

		if ( $is_media_formats_page ) {
			wp_enqueue_script_module(
				'@cb-core/media-formats',
				CB_CORE_URL . 'assets/js/features/media-formats.js',
				[],
				CB_CORE_VERSION
			);
		}

		if ( $is_content_models_page ) {
			\CB\Core\UI\Assets::enqueue_icon_picker( \CB\Core\UI\Assets::ICON_PICKER_PRESENTATION_CORE );
			\CB\Core\UI\Assets::enqueue_capability_picker( \CB\Core\UI\Assets::CAPABILITY_PICKER_PRESENTATION_CORE );
		}

		if ( $is_content_models_field_groups ) {
			\CB\Core\UI\Assets::enqueue_modals( \CB\Core\UI\Assets::MODAL_PRESENTATION_CORE );
			\CB\Core\UI\Assets::enqueue_select_picker( \CB\Core\UI\Assets::SELECT_PICKER_PRESENTATION_CORE );
			$content_models_deps = [ '@cb-core/modal', '@cb-core/select-picker' ];

			wp_enqueue_script_module(
				'@cb-core/content-models',
				CB_CORE_URL . 'assets/js/features/content-models.js',
				$content_models_deps,
				CB_CORE_VERSION
			);
			add_filter(
				'script_module_data_@cb-core/content-models',
				static function ( array $existing ): array {
					return array_merge( $existing, [
						'ajaxUrl' => admin_url( 'admin-ajax.php' ),
						'i18n' => [
							'typeChangeTitle'   => __( 'Change field type?', 'core-blueprint' ),
							'typeChangeBody'    => __( 'Changing a field type can change how existing WordPress metadata is interpreted. Core Blueprint will not delete or migrate existing field values. If this field is new or unused, changing the type is normally safe. If it already contains data, review affected content after saving.', 'core-blueprint' ),
							'typeChangeConfirm' => __( 'Change field type', 'core-blueprint' ),
							'typeChangeCancel'  => __( 'Keep current type', 'core-blueprint' ),
							'quickSaving'       => __( 'Saving…', 'core-blueprint' ),
							'quickSaved'        => __( 'Field saved.', 'core-blueprint' ),
							'quickError'        => __( 'The field could not be saved.', 'core-blueprint' ),
							'requiredLabel'     => __( 'required', 'core-blueprint' ),
							'restEnabled'       => __( 'Enabled', 'core-blueprint' ),
							'restDisabled'      => __( 'Disabled', 'core-blueprint' ),
						],
					] );
				}
			);
		}


		// ─── Scrollbar (1.6.4-dev) ───────────────────────────────────────
		//
		// Suite-wide thin scrollbar primitive. Loaded right after tokens
		// and before any other component or page CSS so the styling
		// reaches every scrollable Core Admin surface. Asset handles are
		// implementation details; extension pages consume the registered
		// Core Admin shell/semantic requirements rather than handle names.
		wp_enqueue_style(
			'cb-core-css-scrollbar',
			CB_CORE_URL . 'assets/css/components/scrollbar.css',
			[ 'cb-core-css-tokens' ],
			CB_CORE_VERSION
		);

		// ─── Meta strip (1.6.4-dev) ──────────────────────────────────────
		//
		// Suite-wide page-metadata strip - the row of contextual facts
		// that sits under a page title (totals, retention, access
		// rules, export options). Generic class names (cb-core-meta /
		// cb-core-meta__item) - not log-specific - so registered Core Admin
		// pages can reuse the same markup without depending on private handles.
		wp_enqueue_style(
			'cb-core-css-meta',
			CB_CORE_URL . 'assets/css/components/meta.css',
			[ 'cb-core-css-tokens' ],
			CB_CORE_VERSION
		);

		// ─── Mode switcher (1.6.4-dev) ───────────────────────────────────
		//
		// Suite-wide reading-mode switcher (Plain / Technical / Sync).
		// Identical markup + behaviour across every CB page and the
		// HUD - one mental model for the user, one source of truth
		// for the markup contract. Two size variants via the
		// --compact modifier; see UI::render_mode_switcher() for the
		// rendering API.
		wp_enqueue_style(
			'cb-core-css-mode-switcher',
			CB_CORE_URL . 'assets/css/components/mode-switcher.css',
			[ 'cb-core-css-tokens' ],
			CB_CORE_VERSION
		);

		// ─── Filter bar (1.6.4-dev) ──────────────────────────────────────
		//
		// Suite-wide filter bar - the row of labelled controls above
		// any list/table view (Logs, Notes, Reports, Hub fleet, …).
		// One uniform control height (--cb-control-height), labels
		// for every field including the actions cluster, responsive
		// flex-wrap on narrow viewports. Depends on mode-switcher
		// so the ms-specific filter-bar overrides resolve in order.
		wp_enqueue_style(
			'cb-core-css-filter-bar',
			CB_CORE_URL . 'assets/css/components/filter-bar.css',
			[ 'cb-core-css-tokens', 'cb-core-css-mode-switcher' ],
			CB_CORE_VERSION
		);

		// ─── Layout + foundational components ─────────────────────────────
		//
		// Layout primitives (page-wrap, title, intro, h2) and components
		// that other components or pages may override later in the
		// cascade. Loading them in this fixed order is what gives us
		// predictable specificity even though selectors are flat.
		wp_enqueue_style(
			'cb-core-css-layout',
			CB_CORE_URL . 'assets/css/layout.css',
			[ 'cb-core-css-tokens' ],
			CB_CORE_VERSION
		);
		$cb_core_css_components_foundation = [
			'tile-grid',
			'kv-tables',
			'badges',
			'rack-modules',
			'inert-text',
			'meta-bar',
			'panels',
			'utility',
			'policy-table',
			'overview-framework',
			'form-status',
			'disclosure',
			'hud',
		];
		foreach ( $cb_core_css_components_foundation as $component ) {
			wp_enqueue_style(
				'cb-core-css-' . $component,
				CB_CORE_URL . 'assets/css/components/' . $component . '.css',
				[ 'cb-core-css-tokens' ],
				CB_CORE_VERSION
			);
		}

		// ─── Components introduced in stap 5.1 ────────────────────────────
		//
		// Newer components designed against the cb-* token contract from
		// the start. Loaded after foundation components so they can
		// override default styling where the new component is intended
		// to supersede a foundation pattern (e.g. .cb-core-modal supersedes
		// older modal patterns).
		$cb_core_css_components_modern = [
			'cards',
			'modals',
			'toasts',
			'buttons',
			'interactive-surfaces',
			'state-badges',
			'status-indicators',
			'spinner',
			'empty-state',
			'nav-tabs',
			'table-cols',
			'actions',
			'log-table',
			'field',
			'radio-card',
			'master-switch',
			'form-controls',
			'choice-group',
			'status-menu',
			'notices',
		];
		foreach ( $cb_core_css_components_modern as $component ) {
			wp_enqueue_style(
				'cb-core-css-' . $component,
				CB_CORE_URL . 'assets/css/components/' . $component . '.css',
				[ 'cb-core-css-tokens' ],
				CB_CORE_VERSION
			);
		}

		// ─── Theme-level overrides ────────────────────────────────────────
		//
		// Canvas overrides target WP admin chrome (page background, admin
		// notices) per CB theme. Theme-level concern, not page or
		// component. Loaded after components so theme-specific surface
		// colours apply on top of component baselines.
		wp_enqueue_style(
			'cb-core-css-theme-canvas',
			CB_CORE_URL . 'assets/css/themes/canvas.css',
			[ 'cb-core-css-tokens' ],
			CB_CORE_VERSION
		);

		// ─── Page-specific stylesheets ────────────────────────────────────
		//
		// Per-page styling. Loaded last so any page-specific overrides on
		// shared components (banners, badges, kv-tables) take precedence.
		// Page selectors are unique to each page so cascade collisions
		// between pages are not expected.
		//
		// Naming convention: top-level admin pages get a single-word
		// filename (dashboard, logs, reports, privacy). Pages that are
		// tabs of a parent page use {parent}-{tab}.css so the structure
		// is visible from the file listing.
		$cb_core_css_pages = [
			'dashboard',
			'logs',
			'reports',
			'preferences',
			'privacy',
			'appearance',
			'language',
			'security',
			'preferences-notifications',
			'preferences-permissions',
			'preferences-cli',
			'console',
			'mail',
			'safeguards-modules',
			'safeguards-failsafe',
			'safeguards-login-shield',
			'safeguards-site-mode',
			'safeguards-core-shield',
			'safeguards-core-scanner',
			'notes',
			'user-roles',
			'media-replace',
			'media-formats',
			'content-models',
		];
		foreach ( $cb_core_css_pages as $page ) {
			wp_enqueue_style(
				'cb-core-css-page-' . $page,
				CB_CORE_URL . 'assets/css/pages/' . $page . '.css',
				[ 'cb-core-css-tokens' ],
				CB_CORE_VERSION
			);
		}

		if ( $is_hud_menu_preferences ) {
			wp_enqueue_style(
				'cb-core-css-page-preferences-floating-menu',
				CB_CORE_URL . 'assets/css/pages/preferences-floating-menu.css',
				[ 'cb-core-css-tokens', 'cb-core-css-buttons', 'cb-core-css-form-controls', 'cb-core-css-state-badges', 'cb-core-css-page-preferences' ],
				CB_CORE_VERSION
			);
		}

		// ─── ES module layer (v1.1.1) ───────────────────────────────────
		//
		// CB Base ships native ES script-modules. Each module is registered
		// under the WP-conventional `@cb-core/{name}` ID (mirrors WP core's
		// `@wordpress/...` namespace). Per-module server-side data is
		// delivered via the official `script_module_data_{$id}` filter
		// (introduced in WP 6.7) - WP prints a `<script type="application/json"
		// id="wp-script-module-data-@cb-core/{name}">…</script>` tag that
		// each module reads via DOM lookup at runtime.
		//
		// Runtime cross-plugin API surface (modal, toast, qs, qsa, apiPost,
		// setTheme, setLocale, copyToClipboard, confirmPassword, apiVersion)
		// continues to attach to `window.cbCore` from inside core/* modules
		// - that is intentional and lets extension plugins call CB helpers
		// without cross-plugin filesystem imports.
		//
		// Module imports resolve via filesystem-style relative paths inside
		// each plugin (e.g. `import { qs } from '../core/dom.js'`) - no
		// bundler, no build step. The $deps argument here only controls
		// load-order in the HTML; the browser handles actual resolution.

		$admin_nonce = wp_create_nonce( 'cb_core_admin' );
		$ajax_url    = admin_url( 'admin-ajax.php' );

		// Common save-status strings - duplicated across modules that need
		// them. Source-side DRY without adding cross-module data leakage.
		$save_status = [
			'saving'          => __( 'Saving…', 'core-blueprint' ),
			'saved'           => __( 'Saved', 'core-blueprint' ),
			'saveFailed'      => __( 'Could not save - try again', 'core-blueprint' ),
			'saveFailedShort' => __( 'Save failed.', 'core-blueprint' ),
			'networkError'    => __( 'Network error - try again.', 'core-blueprint' ),
		];

		$cb_core_js_modules = [
			// ─── Core modules - shared infrastructure ────────────────────
			[
				'id'   => '@cb-core/dom',
				'src'  => 'core/dom.js',
				'deps' => [],
				'data' => [
					'ajaxUrl' => $ajax_url,
					'i18n'    => [
						'copiedToClipboard' => __( 'Copied to clipboard', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/toast',
				'src'  => 'core/toast.js',
				'deps' => [],
				'data' => [
					'presentation' => 'core',
					'i18n' => [
						'dismiss' => __( 'Dismiss notification', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/busy',
				'src'  => 'core/busy.js',
				'deps' => [],
				'data' => null,
			],
			[
				'id'   => '@cb-core/modal',
				'src'  => 'core/modal.js',
				'deps' => [ '@cb-core/icon' ],
				'data' => [
					'presentation' => 'core',
					'i18n' => [
						'confirm'          => __( 'Confirm', 'core-blueprint' ),
						'cancel'           => __( 'Cancel', 'core-blueprint' ),
						'close'            => __( 'Close', 'core-blueprint' ),
						'typeToConfirm'    => __( 'Type to confirm:', 'core-blueprint' ),
						'textDoesNotMatch' => __( 'Text does not match.', 'core-blueprint' ),
						'input'            => __( 'Input', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/public-api',
				'src'  => 'core/public-api.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonceTheme'  => wp_create_nonce( 'cb_core_theme' ),
					'nonceLocale' => wp_create_nonce( 'cb_core_locale' ),
				],
			],
			[
				// Suite-wide reading-mode switcher behaviour. Wires every
				// .cb-core-mode-switcher on the page (HUD + page-level)
				// to the shared AJAX endpoint, then dispatches a
				// cancelable `cb-core-mode-changed` event. Pages that
				// need a hard reload (Logs) listen for the event and
				// preventDefault; pages that flip .cb-core-dual blocks
				// soft-update via the default handler.
				'id'   => '@cb-core/mode-switcher',
				'src'  => 'core/mode-switcher.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'modeChangeFailed' => __( 'Could not change reading mode.', 'core-blueprint' ),
					],
				],
			],


			[
				'id'   => '@cb-core/status-menu',
				'src'  => 'core/status-menu.js',
				'deps' => [],
				'data' => null,
			],

			[
				'id'   => '@cb-core/module-activation',
				'src'  => 'features/module-activation.js',
				'deps' => [ '@cb-core/dom', '@cb-core/toast' ],
				'data' => [
					'nonce'   => $admin_nonce,
					'modules' => class_exists( '\\CB\\Core\\Modules\\ActivationRegistry' )
						? \CB\Core\Modules\ActivationRegistry::slugs()
						: [],
					'i18n'    => [
						'updateFailed' => __( 'Could not update module - try again.', 'core-blueprint' ),
					],
				],
			],

			// ─── Feature modules - Preferences pages ─────────────────────
			[
				'id'   => '@cb-core/appearance',
				'src'  => 'features/appearance.js',
				'deps' => [ '@cb-core/dom', '@cb-core/public-api' ],
				'data' => [
					'i18n' => [
						'saved'      => $save_status['saved'],
						'saveFailed' => $save_status['saveFailed'],
					],
				],
			],
			[
				'id'   => '@cb-core/language',
				'src'  => 'features/language.js',
				'deps' => [ '@cb-core/dom', '@cb-core/public-api' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'saved'      => $save_status['saved'],
						'saveFailed' => $save_status['saveFailed'],
					],
				],
			],
			[
				'id'   => '@cb-core/notifications',
				'src'  => 'features/notifications.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonce' => $admin_nonce,
				],
			],
			[
				'id'   => '@cb-core/alert-recipients',
				'src'  => 'features/alert-recipients.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'lsSaving'            => $save_status['saving'],
						'lsSaved'             => $save_status['saved'],
						'recipientSaveFailed' => __( 'Could not save recipient - try again.', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/privacy',
				'src'  => 'features/privacy.js',
				'deps' => [ '@cb-core/dom', '@cb-core/modal', '@cb-core/toast' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'saving'                => $save_status['saving'],
						'saved'                 => $save_status['saved'],
						'saveFailed'            => $save_status['saveFailed'],
						'confirmPreset'         => __( 'Apply this preset? All current settings will be overwritten.', 'core-blueprint' ),
						'confirmPresetTitle'    => __( 'Apply this preset?', 'core-blueprint' ),
						'confirmPresetConfirm'  => __( 'Apply preset', 'core-blueprint' ),
						'privacyPresetFailed'   => __( 'Could not apply preset.', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/reports-preferences',
				'src'  => 'features/reports-preferences.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'i18n' => array_merge(
						$save_status,
						[
							'reportsNonceMissing'         => __( 'Nonce missing - reload the page.', 'core-blueprint' ),
							'reportsMasterToggleFailed'   => __( 'Could not update Reports - try again.', 'core-blueprint' ),
							'brandingNoLogo'              => __( 'No logo set', 'core-blueprint' ),
							'brandingSelectLogo'          => __( 'Select logo', 'core-blueprint' ),
							'brandingChangeLogo'          => __( 'Change logo', 'core-blueprint' ),
							'brandingPickerTitle'         => __( 'Select logo', 'core-blueprint' ),
							'brandingPickerButton'        => __( 'Use this image', 'core-blueprint' ),
							'brandingMediaUnavailable'    => __( 'Media Library not available - reload the page.', 'core-blueprint' ),
							'brandingInvalidHex'          => __( 'Hex colour must be in #RRGGBB form.', 'core-blueprint' ),
							'brandingConfirmReset'        => __( 'Reset report settings to defaults? Logo, report provider details, and accent colour will be cleared.', 'core-blueprint' ),
							'brandingConfirmResetTitle'   => __( 'Reset report settings?', 'core-blueprint' ),
							'brandingConfirmResetConfirm' => __( 'Reset to defaults', 'core-blueprint' ),
							'brandingResetting'           => __( 'Resetting…', 'core-blueprint' ),
							'brandingResetDone'           => __( 'Reset to defaults.', 'core-blueprint' ),
						]
					),
				],
			],
			[
				'id'   => '@cb-core/permissions',
				'src'  => 'features/permissions.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'i18n' => [
						'saving'          => $save_status['saving'],
						'saved'           => $save_status['saved'],
						'saveFailedShort' => $save_status['saveFailedShort'],
						'networkError'    => $save_status['networkError'],
					],
				],
			],

			// ─── Feature modules - Safeguards pages ──────────────────────
			[
				'id'   => '@cb-core/site-mode',
				'src'  => 'features/site-mode.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'saving'              => $save_status['saving'],
						'saved'               => $save_status['saved'],
						'saveFailed'          => $save_status['saveFailed'],
						'saveAccessMode'      => __( 'Save Access Mode', 'core-blueprint' ),
						'activatePublic'      => __( 'Activate Public Mode', 'core-blueprint' ),
						'activateComingSoon'  => __( 'Activate Coming Soon', 'core-blueprint' ),
						'activateMaintenance' => __( 'Activate Maintenance', 'core-blueprint' ),
						'activateAdminOnly'   => __( 'Activate Admin-Only', 'core-blueprint' ),
						'accessAdminOnly'     => __( 'Admin-Only Mode - site locked', 'core-blueprint' ),
						'accessComingSoon'    => __( 'Coming Soon - pre-launch page active', 'core-blueprint' ),
						'accessMaintenance'   => __( 'Maintenance - site temporarily unavailable', 'core-blueprint' ),
						'accessPublic'        => __( 'Public Mode - site live', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/core-shield',
				'src'  => 'features/core-shield.js',
				'deps' => [ '@cb-core/dom', '@cb-core/modal', '@cb-core/toast', '@cb-core/busy', '@cb-core/icon' ],
				'data' => [
					'nonce'          => $admin_nonce,
					'privilegedMode' => \CB\Core\Permissions\PrivilegedAccessPolicy::enforcement_mode(),
					'i18n'           => [
						'networkError'                => $save_status['networkError'],
						'shieldApplyDefaultsTitle'    => __( 'Apply recommended defaults?', 'core-blueprint' ),
						'shieldApplyDefaultsBody'     => __( 'This overwrites your current module and feature toggle configuration with the recommended defaults for the current site mode.', 'core-blueprint' ),
						'shieldApplyDefaultsConfirm'  => __( 'Apply defaults', 'core-blueprint' ),
						'headerTestError'             => __( 'Header test failed:', 'core-blueprint' ),
						'headerScore'                 => __( '%1$d of %2$d security headers present - Grade %3$s', 'core-blueprint' ),
						'headerPresent'               => __( 'Present', 'core-blueprint' ),
						'headerMissing'               => __( 'Missing', 'core-blueprint' ),
						'headerGradeLabel'            => __( 'Grade', 'core-blueprint' ),
						'headerColumnHeader'          => __( 'Header', 'core-blueprint' ),
						'headerColumnValue'           => __( 'Value', 'core-blueprint' ),
						'testingHeaders'              => __( 'Running test…', 'core-blueprint' ),
						'privilegedApproveTitle'        => __( 'Approve privileged access?', 'core-blueprint' ),
						'privilegedApproveBody'         => __( 'This immediately restores the account’s administrator-level capabilities for its exact current privilege state. Approve only after verifying that the account is legitimate.', 'core-blueprint' ),
						'privilegedApproveConfirm'      => __( 'Approve access', 'core-blueprint' ),
						'privilegedApproveFailed'       => __( 'Could not approve privileged access.', 'core-blueprint' ),
						'privilegedModeSaveFailed'      => __( 'Could not update Privileged Access Protection.', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/login-shield',
				'src'  => 'features/login-shield.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'lsSaving'                => $save_status['saving'],
						'lsSaved'                 => $save_status['saved'],
						'lsSavedReloading'        => __( 'Saved - reloading…', 'core-blueprint' ),
						'lsSaveFailed'            => __( 'Could not save Login Shield settings - try again.', 'core-blueprint' ),
						'lsTesting'               => __( 'Testing…', 'core-blueprint' ),
						'lsTestFailed'            => __( 'Test request failed.', 'core-blueprint' ),
						'lsConfirmStrict'         => __( "Strict mode blocks /wp-admin for guests - only your custom login URL works. If you forget the URL, you can only get back in via the Failsafe bypass (see Failsafe tab). Continue?", 'core-blueprint' ),
						'lsConfirmStrictTitle'    => __( 'Enable Strict mode?', 'core-blueprint' ),
						'lsConfirmStrictConfirm'  => __( 'Enable Strict mode', 'core-blueprint' ),
						'lsSlugRequired'          => __( 'A custom login URL is required before Login Shield can be enabled.', 'core-blueprint' ),
					],
				],
			],
			[
				'id'   => '@cb-core/failsafe',
				'src'  => 'features/failsafe.js',
				'deps' => [ '@cb-core/dom', '@cb-core/modal', '@cb-core/toast', '@cb-core/busy' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => [
						'networkError'                => $save_status['networkError'],
						'cancel'                      => __( 'Cancel', 'core-blueprint' ),
						'failsafePasswordPlaceholder' => __( 'WordPress password', 'core-blueprint' ),
						'failsafeRotateTitle'         => __( 'Rotate bypass token', 'core-blueprint' ),
						'failsafeRotateBody'          => __( 'This invalidates the current bypass URL immediately. The new URL will be shown only once on the redirected page.' . "\n\n" . 'Re-enter your WordPress password to continue.', 'core-blueprint' ),
						'failsafeRotateConfirm'       => __( 'Rotate token', 'core-blueprint' ),
						'failsafePanicTitle'          => __( 'Activate emergency bypass', 'core-blueprint' ),
						'failsafePanicBody'           => __( 'All restrictive security features will be deactivated until you explicitly resume enforcement.' . "\n\n" . 'Re-enter your WordPress password to confirm.', 'core-blueprint' ),
						'failsafePanicConfirm'        => __( 'Activate bypass', 'core-blueprint' ),
						'failsafeReasonTitle'         => __( 'Reason for activating', 'core-blueprint' ),
						'failsafeReasonBody'          => __( 'Optionally, log why you activated the emergency bypass. This will be visible in the audit log.', 'core-blueprint' ),
						'failsafeReasonConfirm'       => __( 'Activate', 'core-blueprint' ),
						'failsafeReasonPlaceholder'   => __( 'Reason (optional)', 'core-blueprint' ),
						'failsafeResumeTitle'         => __( 'Resume enforcement?', 'core-blueprint' ),
						'failsafeResumeBody'          => __( 'All restrictive security features will be re-enabled. Anyone currently using the bypass URL will lose access immediately.', 'core-blueprint' ),
						'failsafeResumeConfirm'       => __( 'Resume enforcement', 'core-blueprint' ),
					],
				],
			],
			// ─── Feature modules - Logs page ─────────────────────────────
			[
				'id'   => '@cb-core/logs-toggle',
				'src'  => 'features/logs-toggle.js',
				// Listens for the cb-core-mode-changed event dispatched
				// by mode-switcher; needs no nonce of its own.
				'deps' => [ '@cb-core/mode-switcher' ],
				'data' => null,
			],
			[
				'id'   => '@cb-core/log-exports',
				'src'  => 'features/log-exports.js',
				'deps' => [],
				'data' => [
					'nonce'   => $admin_nonce,
					'ajaxUrl' => $ajax_url,
				],
			],

			// ─── Feature modules - Reports page ──────────────────────────
			[
				'id'   => '@cb-core/reports',
				'src'  => 'features/reports.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'nonce' => $admin_nonce,
					'i18n'  => array_merge(
						$save_status,
						[
							'reportsSelectPeriod'      => __( 'Select a period.', 'core-blueprint' ),
							'reportsNonceMissing'      => __( 'Nonce missing - reload the page.', 'core-blueprint' ),
							'reportsGenerating'        => __( 'Generating…', 'core-blueprint' ),
							'reportsGenerateFailed'    => __( 'Generation failed - see audit log for details.', 'core-blueprint' ),
							'reportsGenerated'         => __( 'Report generated.', 'core-blueprint' ),
							'reportsViewOnOverview'    => __( 'View on Overview', 'core-blueprint' ),
							'reportsNoneYet'           => __( 'No reports generated yet on this site.', 'core-blueprint' ),
							'reportsDeleteOneTitle'    => __( 'Delete this report?', 'core-blueprint' ),
							'reportsDeleteOneBody'     => __( 'The stored report snapshot will be removed and this cannot be undone.', 'core-blueprint' ),
							'reportsDeleteOneConfirm'  => __( 'Delete', 'core-blueprint' ),
							'reportsDeleteAllTitle'    => __( 'Delete all reports?', 'core-blueprint' ),
							'reportsDeleteAllBody'     => __( 'This permanently removes every stored Maintenance Report snapshot on this site. This action cannot be undone.', 'core-blueprint' ),
							'reportsDeleteAllConfirm'  => __( 'Delete all reports', 'core-blueprint' ),
							'reportsDeleteAllHint'     => __( 'Type the phrase to confirm:', 'core-blueprint' ),
							'reportsDeleteAllDone'     => __( 'All reports deleted.', 'core-blueprint' ),
						]
					),
				],
			],

			// ─── Feature modules - Description toggle (cross-page) ───────
			[
				'id'   => '@cb-core/description-toggle',
				'src'  => 'features/description-toggle.js',
				'deps' => [ '@cb-core/dom' ],
				'data' => [
					'descMode' => [
						'current' => class_exists( UI::class ) ? UI::current_mode() : 'plain',
					],
					'i18n' => [
						'labelTech'     => __( 'tech', 'core-blueprint' ),
						'labelPlain'    => __( 'plain', 'core-blueprint' ),
						'showTechnical' => __( 'Show technical description', 'core-blueprint' ),
						'showPlain'     => __( 'Show plain description', 'core-blueprint' ),
					],
				],
			],

			// ─── Feature modules - Core Scanner (Safeguards tab) ─────────
			[
				'id'   => '@cb-core/core-scanner',
				'src'  => 'features/core-scanner.js',
				'deps' => [ '@cb-core/dom', '@cb-core/busy', '@cb-core/modal', '@cb-core/toast' ],
				'data' => [
					'restUrl'   => esc_url_raw( rest_url( 'core-blueprint/v1/integrity/admin' ) ),
					'nonce'     => wp_create_nonce( 'wp_rest' ),
					'activeJob' => self::core_scanner_active_job_data(),
					'i18n'    => [
						// Action / status messages
						'running'                   => __( 'Running Core Scanner…',                       'core-blueprint' ),
						'complete'                  => __( 'Core scan completed.',                       'core-blueprint' ),
						'failed'                    => __( 'Core scan failed.',                          'core-blueprint' ),
						'saving'                    => __( 'Saving settings…',                           'core-blueprint' ),
						'saved'                     => __( 'Settings saved.',                            'core-blueprint' ),
						'clearing'                  => __( 'Clearing results…',                          'core-blueprint' ),
						'cleared'                   => __( 'Results cleared.',                           'core-blueprint' ),
						'clearFailed'               => __( 'Clear failed.',                              'core-blueprint' ),
						'approvingBaseline'         => __( 'Approving baseline…',                        'core-blueprint' ),
						'baselineApproved'          => __( 'Baseline approved.',                         'core-blueprint' ),
						'baselineFailed'            => __( 'Baseline approval failed.',                  'core-blueprint' ),
						'baselineReviewing'         => __( 'Saving review…',                           'core-blueprint' ),
						'baselineReviewed'          => __( 'Baseline candidate marked as reviewed.',           'core-blueprint' ),
						'baselineReviewFailed'      => __( 'Could not save baseline review.',                  'core-blueprint' ),
						'removingBaseline'          => __( 'Removing from baseline…',                    'core-blueprint' ),
						'baselineRemoved'           => __( 'Removed from approved baseline.',            'core-blueprint' ),
						'baselineRemoveFailed'      => __( 'Removal failed.',                            'core-blueprint' ),
						'clearingBaseline'          => __( 'Clearing baseline…',                         'core-blueprint' ),
						'baselineCleared'           => __( 'Approved baseline cleared.',                 'core-blueprint' ),
						'baselineClearFailed'       => __( 'Clear failed.',                              'core-blueprint' ),

						// Modal titles + bodies + buttons
						'clearTitle'                => __( 'Clear scan results',                         'core-blueprint' ),
						'confirmClear'              => __( 'Clear the stored integrity scan result? Files on this site will not be modified.', 'core-blueprint' ),
						'clearConfirm'              => __( 'Clear results',                              'core-blueprint' ),
						'baselineTitle'             => __( 'Approve all local baselines',                'core-blueprint' ),
						'baselineUpdateTitle'       => __( 'Update all local baselines',                 'core-blueprint' ),
						'confirmBaseline'           => __( 'Bulk-approve every eligible plugin and theme snapshot from the latest scan as a local baseline. Review the listed components first; future scans will treat these exact file states as trusted.', 'core-blueprint' ),
						'confirmBaselineUpdate'     => __( 'Bulk-update every eligible plugin and theme local baseline from the latest scan. Only continue after reviewing the affected components and confirming their current file states are expected.', 'core-blueprint' ),
						'baselineConfirm'           => __( 'Approve all eligible baselines',              'core-blueprint' ),
						'baselineUpdate'            => __( 'Update all eligible baselines',               'core-blueprint' ),
						'componentBaselineTitle'    => __( 'Approve component baseline',                 'core-blueprint' ),
						'componentBaselineConfirm'  => __( 'Approve component',                          'core-blueprint' ),
						'confirmComponentApprove'   => __( 'Approve the current state of {slug} as the local baseline. Future changes for this component will be flagged.', 'core-blueprint' ),
						'confirmComponentUpdate'    => __( 'Update the approved baseline for {slug}. Future scans will compare this component against its current state. Only continue after confirming this change is expected.', 'core-blueprint' ),
						'baselineRemoveTitle'       => __( 'Remove from approved baseline',              'core-blueprint' ),
						'confirmBaselineRemove'     => __( 'Remove {slug} from the approved baseline. The scanner will stop tracking this component. Use this only when the component has been intentionally removed from the site.', 'core-blueprint' ),
						'baselineRemove'            => __( 'Remove from baseline',                       'core-blueprint' ),
						'baselineClearTitle'        => __( 'Clear approved baseline',                    'core-blueprint' ),
						'confirmBaselineClear'      => __( 'Clear the entire approved baseline. All previously approved components will need to be re-verified - run a new scan afterwards to start fresh.', 'core-blueprint' ),
						'baselineClear'             => __( 'Clear Approved Baseline',                    'core-blueprint' ),
						'redetectingLocale'         => __( 'Detecting…',                                 'core-blueprint' ),
						'scanAlreadyRunning'        => __( 'A scan is already running. Progress has been restored.', 'core-blueprint' ),
						'scanLost'                  => __( 'Scan progress lost. Reloading.',             'core-blueprint' ),
						'phaseStarting'             => __( 'Starting…',                                  'core-blueprint' ),
						'phaseCore'                 => __( 'Verifying core files',                       'core-blueprint' ),
						'phasePlugins'              => __( 'Verifying plugins',                          'core-blueprint' ),
						'phaseThemes'               => __( 'Verifying themes',                           'core-blueprint' ),
						'phaseUploads'              => __( 'Scanning uploads',                           'core-blueprint' ),
						'runningScan'               => __( 'Running Core Scanner',                       'core-blueprint' ),
						'scanProgressAria'          => __( 'Scan progress',                              'core-blueprint' ),
						'localeDetected'            => __( 'Distribution locale detected: {locale}',     'core-blueprint' ),
						'localeInconclusive'        => __( 'Detection inconclusive - see panel for details.', 'core-blueprint' ),
						'localeDetectFailed'        => __( 'Detection failed.',                          'core-blueprint' ),
						'cancel'                    => __( 'Cancel',                                     'core-blueprint' ),
						'confirm'                   => __( 'Confirm',                                    'core-blueprint' ),
						'copyPath'                  => __( 'Copy path',                                   'core-blueprint' ),
						'pathCopied'                => __( 'Filesystem path copied.',                    'core-blueprint' ),
						'pathCopyFailed'            => __( 'Could not copy the filesystem path.',        'core-blueprint' ),
						'quarantineFileTitle'       => __( 'Quarantine file', 'core-blueprint' ),
						'quarantineDirectoryTitle'  => __( 'Quarantine folder', 'core-blueprint' ),
						'quarantineFileBody'        => __( 'Move this exact scanned file out of the active site and into the private Quarantine Workspace? Its SHA-256 is re-verified immediately before the move.', 'core-blueprint' ),
						'quarantineDirectoryBody'   => __( 'Move this finding’s top-level uploads directory out of the active site and into the private Quarantine Workspace? Every file is re-verified first; symlinks or changed evidence abort the action.', 'core-blueprint' ),
						'quarantineConfirm'         => __( 'Quarantine', 'core-blueprint' ),
						'quarantining'              => __( 'Quarantining…', 'core-blueprint' ),
						'quarantineDone'            => __( 'Item moved to Quarantine Workspace.', 'core-blueprint' ),
						'quarantineInspectTitle'    => __( 'Inspect quarantined item', 'core-blueprint' ),
						'quarantineOriginalPath'    => __( 'Original location', 'core-blueprint' ),
						'quarantineStatus'          => __( 'Status', 'core-blueprint' ),
						'quarantineFiles'           => __( 'Files', 'core-blueprint' ),
						'quarantineNoPreview'       => __( 'No safe text preview is available for this file.', 'core-blueprint' ),
						'quarantinePreviewTruncated'=> __( 'Preview truncated.', 'core-blueprint' ),
						'quarantineRestoreTitle'    => __( 'Restore quarantined item', 'core-blueprint' ),
						'quarantineRestoreBody'     => __( 'Restore this item to its exact original location? Restore is refused if anything now exists at that path or if the quarantine payload changed.', 'core-blueprint' ),
						'quarantineRestore'         => __( 'Restore', 'core-blueprint' ),
						'quarantineRestoring'       => __( 'Restoring…', 'core-blueprint' ),
						'quarantineRestored'        => __( 'Quarantine item restored.', 'core-blueprint' ),
						'quarantineDeleteTitle'     => __( 'Permanently delete quarantined item', 'core-blueprint' ),
						'quarantineDeleteBody'      => __( 'This permanently destroys the isolated payload. The workspace record and audit trail remain, but the file cannot be restored.', 'core-blueprint' ),
						'quarantineDelete'          => __( 'Permanently delete', 'core-blueprint' ),
						'quarantineDeleteHint'      => __( 'Type to confirm:', 'core-blueprint' ),
						'quarantineDeleting'        => __( 'Deleting…', 'core-blueprint' ),
						'quarantineDeleted'         => __( 'Quarantine payload permanently deleted.', 'core-blueprint' ),
						'quarantineNoteTitle'       => __( 'Add quarantine note', 'core-blueprint' ),
						'quarantineNoteBody'        => __( 'Add investigation context for this item. Notes become part of the workspace history.', 'core-blueprint' ),
						'quarantineNoteSave'        => __( 'Save note', 'core-blueprint' ),
						'quarantineNotePlaceholder' => __( 'Investigation note…', 'core-blueprint' ),
						'quarantineNoteSaved'       => __( 'Quarantine note saved.', 'core-blueprint' ),
						'quarantineStateSaved'      => __( 'Quarantine review state updated.', 'core-blueprint' ),
						'close'                     => __( 'Close', 'core-blueprint' ),

						// Render labels

						// Diff

						// Baseline summary

						// History
					],
				],
			],
			// ─── Feature modules - Notes (top-level page) ────────────────
			[
				'id'   => '@cb-core/notes',
				'src'  => 'features/notes.js',
				'deps' => [ '@cb-core/dom', '@cb-core/modal', '@cb-core/toast', '@cb-core/busy' ],
				'data' => [
					'restRoot' => esc_url_raw( rest_url( 'core-blueprint/v1/notes/' ) ),
					'nonce'    => wp_create_nonce( 'wp_rest' ),
					'settings' => class_exists( '\\CB\\Core\\Notes\\Settings\\SettingsRepository' )
						? \CB\Core\Notes\Settings\SettingsRepository::all()
						: [],
					'i18n'     => [
						'noteSelected'      => __( '%d note selected.', 'core-blueprint' ),
						'notesSelected'     => __( '%d notes selected.', 'core-blueprint' ),
						'note'              => __( 'Note', 'core-blueprint' ),
						'addNote'           => __( 'Add note', 'core-blueprint' ),
						'saveChanges'       => __( 'Save changes', 'core-blueprint' ),
						'cancel'            => __( 'Cancel', 'core-blueprint' ),
						'saved'             => __( 'Saved', 'core-blueprint' ),
						'requestFailed'     => __( 'Request failed', 'core-blueprint' ),
						'importNotes'       => __( 'Import Notes', 'core-blueprint' ),
						'importNotesAction' => __( 'Import notes', 'core-blueprint' ),
						'importReview'      => __( 'Review the imported notes before saving them. Existing notes are detected by context or title.', 'core-blueprint' ),
						'noImportableNotes' => __( 'No importable notes found.', 'core-blueprint' ),
						'untitledNote'      => __( 'Untitled note', 'core-blueprint' ),
						'noChanges'         => __( 'No changes', 'core-blueprint' ),
						'importDecision'    => __( 'Import decision', 'core-blueprint' ),
						'skip'              => __( 'Skip', 'core-blueprint' ),
						'importAsNew'       => __( 'Import as new', 'core-blueprint' ),
						'importAsCopy'      => __( 'Import as copy', 'core-blueprint' ),
						'overwriteExisting' => __( 'Overwrite existing', 'core-blueprint' ),
						'notesImported'     => __( 'Notes imported.', 'core-blueprint' ),
						'importStateNew'    => __( 'New', 'core-blueprint' ),
						'importStateChanged' => __( 'Changed', 'core-blueprint' ),
						'importStateIdentical' => __( 'Identical', 'core-blueprint' ),
					],
				],
			],
			// ─── Feature modules - User Roles ────────────────────────────
			[
				'id'   => '@cb-core/user-roles',
				'src'  => 'features/user-roles.js',
				'deps' => [ '@cb-core/modal', '@cb-core/toast', '@cb-core/icon' ],
				'data' => [
					'restRoot' => esc_url_raw( rest_url( 'core-blueprint/v1/roles' ) ),
					'nonce'    => wp_create_nonce( 'wp_rest' ),
					'i18n'     => [
						'requestFailed'                 => __( 'Could not load or update user roles.', 'core-blueprint' ),
						'noRoles'                       => __( 'No roles found.', 'core-blueprint' ),
						'selectRole'                    => __( 'Select a role', 'core-blueprint' ),
						'system'                        => __( 'System', 'core-blueprint' ),
						'systemRole'                    => __( 'System role', 'core-blueprint' ),
						'wordpress'                     => __( 'WordPress', 'core-blueprint' ),
						'defaultRole'                   => __( 'Default', 'core-blueprint' ),
						'oneUser'                       => __( '%d user', 'core-blueprint' ),
						'manyUsers'                     => __( '%d users', 'core-blueprint' ),
						'protectedBecause'              => __( 'Protected', 'core-blueprint' ),
						'roleName'                      => __( 'Role name', 'core-blueprint' ),
						'roleSlug'                      => __( 'Role slug', 'core-blueprint' ),
						'slugHelp'                      => __( 'Permanent machine name. It cannot be changed later.', 'core-blueprint' ),
						'saveName'                      => __( 'Save name', 'core-blueprint' ),
						'duplicate'                     => __( 'Duplicate', 'core-blueprint' ),
						'duplicateRole'                 => __( 'Duplicate role', 'core-blueprint' ),
						'deleteRole'                    => __( 'Delete role', 'core-blueprint' ),
						'capabilities'                  => __( 'Capabilities', 'core-blueprint' ),
						'capabilityHelp'                => __( 'Primitive WordPress permissions assigned to this role.', 'core-blueprint' ),
						'saveCapabilities'              => __( 'Save capabilities', 'core-blueprint' ),
						'searchCapabilities'            => __( 'Search capabilities', 'core-blueprint' ),
						'searchCapabilitiesPlaceholder' => __( 'Search by name or capability…', 'core-blueprint' ),
						'source'                        => __( 'Source', 'core-blueprint' ),
						'allSources'                    => __( 'All sources', 'core-blueprint' ),
						'noCapabilities'                => __( 'No capabilities match the current filters.', 'core-blueprint' ),
						'required'                      => __( 'Required', 'core-blueprint' ),
						'policyGrant'                   => __( 'Granted by policy', 'core-blueprint' ),
						'outsideAuthority'              => __( 'Outside your authority', 'core-blueprint' ),
						'createRole'                    => __( 'Add role', 'core-blueprint' ),
						'create'                        => __( 'Create role', 'core-blueprint' ),
						'cancel'                        => __( 'Cancel', 'core-blueprint' ),
						'nameSlugRequired'              => __( 'Role name and slug are required.', 'core-blueprint' ),
						'startEmpty'                    => __( 'Start with no capabilities', 'core-blueprint' ),
						'copyFrom'                      => __( 'Copy from', 'core-blueprint' ),
						'capabilityTemplate'            => __( 'Capability template', 'core-blueprint' ),
						'deleteWarning'                 => __( 'This permanently removes the role definition. Users must be reassigned before a role can be deleted.', 'core-blueprint' ),
						'typeSlug'                      => __( 'Type the role slug to confirm:', 'core-blueprint' ),
						'saved'                         => __( 'Saved.', 'core-blueprint' ),
					],
				],
			],


			// ─── Feature modules - CB Console runner (1.6.0-dev) ───────────
			//
			// Three-panel command runner - picker, args form, output. Pure
			// browser-side; talks to /core-blueprint/v1/console/ for the
			// catalog and per-run dispatch. Server-side data is the REST
			// root + nonce + i18n labels for the form widgets and status
			// banners.
			[
				'id'   => '@cb-core/console',
				'src'  => 'features/console.js',
				'deps' => [],
				'data' => [
					'restRoot' => esc_url_raw( rest_url( 'core-blueprint/v1/console/' ) ),
					'nonce'    => wp_create_nonce( 'wp_rest' ),
					'i18n'     => [
						'filterCommands'     => __( 'Filter commands…', 'core-blueprint' ),
						'selectCommand'      => __( 'Select a command', 'core-blueprint' ),
						'selectCommandHelp'  => __( 'Pick a command from the list to view its arguments.', 'core-blueprint' ),
						'noCommands'         => __( 'No commands match your filter.', 'core-blueprint' ),
						'runCommand'         => __( 'Run command', 'core-blueprint' ),
						'running'            => __( 'Running…', 'core-blueprint' ),
						'capabilityDenied'   => __( 'You do not have permission to use the Console.', 'core-blueprint' ),
						'destructiveLabel'   => __( 'Destructive', 'core-blueprint' ),
						'stateChangeLabel'   => __( 'State-change', 'core-blueprint' ),
						'readOnlyLabel'      => __( 'Read-only', 'core-blueprint' ),
						'sideEffectsNote'    => __( 'This command modifies site state.', 'core-blueprint' ),
						'destructiveBannerNote' => __( 'Destructive action - confirmation required before running.', 'core-blueprint' ),
						'destructiveNote'    => __( 'This command is irreversible.', 'core-blueprint' ),
						'required'           => __( 'required', 'core-blueprint' ),
						'fieldRequired'      => __( 'This field is required.', 'core-blueprint' ),
						'durationMs'         => __( '%d ms', 'core-blueprint' ),
						'noOutput'           => __( '(no output)', 'core-blueprint' ),
						'noOutputYet'        => __( 'Output will appear here after you run a command.', 'core-blueprint' ),
						'errorPrefix'        => __( 'Error', 'core-blueprint' ),
						'warningPrefix'      => __( 'Warning', 'core-blueprint' ),
						'transportError'     => __( 'Network or server error: %s', 'core-blueprint' ),
						'groupObserve'       => __( 'Read-only', 'core-blueprint' ),
						'groupMutate'        => __( 'State-change', 'core-blueprint' ),
						'groupDestructive'   => __( 'Destructive', 'core-blueprint' ),
						'groupOther'         => __( 'Other', 'core-blueprint' ),
						'pickerLoading'      => __( 'Loading commands…', 'core-blueprint' ),
						'argsHeading'        => __( 'Arguments', 'core-blueprint' ),
						'noArgs'             => __( 'This command takes no arguments.', 'core-blueprint' ),
						'lastRunLabel'       => __( 'Last run', 'core-blueprint' ),
						'showData'           => __( 'Show structured data', 'core-blueprint' ),
						'hideData'           => __( 'Hide structured data', 'core-blueprint' ),

						// Modal - destructive confirm
						'confirmDestructiveTitle' => __( 'Destructive action', 'core-blueprint' ),
						'irreversibleNote'   => __( 'This action is irreversible.', 'core-blueprint' ),
						'cancel'             => __( 'Cancel', 'core-blueprint' ),
						'confirmRun'         => __( 'Confirm and run', 'core-blueprint' ),

						// Per-destructive-command action lines
						'actFailsafeDisable1'       => __( 'Activates the emergency bypass.', 'core-blueprint' ),
						'actFailsafeDisable2'       => __( 'All restrictive Core Blueprint features are disabled site-wide.', 'core-blueprint' ),
						'actFailsafeDisable3'       => __( 'Site is exposed to threats CB was configured to block until you re-enable.', 'core-blueprint' ),
						'actFailsafeRotateToken1'   => __( 'Generates a new secret bypass URL token.', 'core-blueprint' ),
						'actFailsafeRotateToken2'   => __( 'The new URL is shown ONCE in a separate dialog and cannot be recovered if not saved.', 'core-blueprint' ),
						'actFailsafeRotateToken3'   => __( 'Any previously-saved bypass URL stops working immediately.', 'core-blueprint' ),
						'actOperatorRemove1'        => __( 'Demotes the user from the cb_operator role.', 'core-blueprint' ),
						'actOperatorRemove2'        => __( 'They lose access to operator-only Core Blueprint surfaces.', 'core-blueprint' ),
						'actOperatorRemove3'        => __( 'If --force is set, this proceeds even when they would be the last operator (lockout risk).', 'core-blueprint' ),
						'actGenericIrreversible'    => __( 'This command is destructive and cannot be undone.', 'core-blueprint' ),

						// Modal - secret-token (rotate-token output)
						'secretTokenTitle'   => __( 'Secret bypass URL - shown once', 'core-blueprint' ),
						'secretTokenWarning' => __( 'Save this URL now. It will not be shown again. If you close this dialog without saving, run rotate-token again to generate a new one.', 'core-blueprint' ),
						'secretTokenInfo1'   => __( 'Using this URL will:', 'core-blueprint' ),
						'secretTokenAction1' => __( 'Disable restrictive features for 60 minutes.', 'core-blueprint' ),
						'secretTokenAction2' => __( 'Rotate the token (single-use).', 'core-blueprint' ),
						'secretTokenAction3' => __( 'Send an email notification to %s.', 'core-blueprint' ),
						'copyToClipboard'    => __( 'Copy URL', 'core-blueprint' ),
						'copied'             => __( 'Copied!', 'core-blueprint' ),
						'copiedFallback'     => __( 'Copied (fallback)', 'core-blueprint' ),
						'iSavedIt'           => __( 'I saved it - close', 'core-blueprint' ),

						// Sensitive-output placeholder in regular output
						'sensitiveOutputNote' => __( 'Sensitive output rendered in a separate dialog and not stored here.', 'core-blueprint' ),

						// User-picker (1.6.2-dev)
						'userSearchPlaceholder' => __( 'Search by login, email, or name…', 'core-blueprint' ),
						'searching'             => __( 'Searching…', 'core-blueprint' ),
						'noUsersFound'          => __( 'No users found.', 'core-blueprint' ),
						'searchFailed'          => __( 'Search failed: %s', 'core-blueprint' ),

						// Async polling (1.6.3-dev)
						'runningTitle'         => __( 'Running…', 'core-blueprint' ),
						'asyncScheduled'       => __( 'Async job scheduled.', 'core-blueprint' ),
						'asyncPending'         => __( 'Waiting for cron to fire…', 'core-blueprint' ),
						'asyncRunning'         => __( 'live polling', 'core-blueprint' ),
						'elapsedSeconds'       => __( 'Elapsed: %ds', 'core-blueprint' ),
						'stopProgress'         => __( 'Stop showing progress', 'core-blueprint' ),
						'asyncStopped'         => __( 'Stopped tracking - the scan continues in the background. Refresh the page to resume tracking, or check Logs once it completes.', 'core-blueprint' ),
						'asyncDoneNoResult'    => __( 'Scan complete. Run `cb scan latest` to see the result.', 'core-blueprint' ),
						'asyncFailedGeneric'   => __( 'The scan failed.', 'core-blueprint' ),
						'asyncGone'            => __( 'Progress state expired. The scan may have completed - check Logs and run `cb scan latest`.', 'core-blueprint' ),
					],
				],
			],

			// ─── Feature modules - HUD launcher (cross-page) ──────────────
			//
			// The floating "front door" launcher - drag-to-dock toggle
			// button + slide-in panel. Renders on every CB Base admin page
			// for capable users; on third-party admin pages and frontend
			// the same module is enqueued via HUD\Assets::do_enqueue() on
			// admin_enqueue_scripts/wp_enqueue_scripts hooks. This entry
			// keeps CB Base's own pages on the central enqueue path so
			// dependency ordering and per-module data filters stay in one
			// declarative table.
			[
				'id'   => '@cb-core/hud',
				'src'  => 'features/hud.js',
				'deps' => [],
				'data' => class_exists( \CB\Core\HUD\Assets::class )
					? ( \CB\Core\HUD\Assets::script_module_data( [] ) )
					: [],
			],
		];

		foreach ( $cb_core_js_modules as $module ) {
			wp_enqueue_script_module(
				$module['id'],
				CB_CORE_URL . 'assets/js/' . $module['src'],
				$module['deps'],
				CB_CORE_VERSION
			);

			// Register the per-module data filter only when the module
			// actually needs server-side data. WP prints the JSON tag only
			// for modules with non-empty data, so silent modules (modal,
			// toast) don't pollute the page head.
			if ( ! empty( $module['data'] ) ) {
				$module_id   = $module['id'];
				$module_data = $module['data'];
				add_filter(
					"script_module_data_{$module_id}",
					static function ( array $existing ) use ( $module_data ): array {
						return array_merge( $existing, $module_data );
					}
				);
			}
		}

		// Snippets owns CodeMirror plus its page-only editor glue. The helper
		// is a no-op outside the registered Snippets admin page.
		\CB\Core\Snippets\Admin\Assets::enqueue( $hook );

		// Lazy-load WP Media Library on the Preferences page so the Report
		// Branding tab's logo picker can use wp.media. Loaded conditionally
		// rather than globally - Media Library is several KB of JS we
		// shouldn't drag onto pages that don't need it.
		if ( $hook === ( CB_CORE_PARENT_MENU . '_page_core-blueprint-preferences' ) ) {
			wp_enqueue_media();
		}
	}

	/**
	 * Expose the authoritative active Scanner job to the admin module.
	 *
	 * localStorage is only a convenience cache. A scheduled/API scan can exist
	 * without it, and a browser may retain an older job id after recovery.
	 */
	private static function core_scanner_active_job_data(): ?array {
		if ( ! class_exists( \CB\Core\Integrity\Scanner\ScanJobStatus::class ) ) {
			return null;
		}

		$job = \CB\Core\Integrity\Scanner\ScanJobStatus::active_job();
		if ( ! is_array( $job ) ) {
			return null;
		}

		return [
			'jobId'     => (string) ( $job['job_id'] ?? '' ),
			'startedAt' => (float) ( $job['started_at_micro'] ?? microtime( true ) ),
		];
	}

	// ─── Menu icon helper ────────────────────────────────────────────────

	private static function get_menu_icon(): string {
		$icon_path = CB_CORE_DIR . 'assets/core-blueprint-icon.svg';
		if ( ! file_exists( $icon_path ) ) {
			return 'dashicons-shield-alt';
		}
		$svg = file_get_contents( $icon_path );
		if ( false === $svg ) {
			return 'dashicons-shield-alt';
		}
		return 'data:image/svg+xml;base64,' . base64_encode( $svg );
	}
}
